Princeton-LSI-ResearchComputing/tracebase

.github/pull_request_template.md, .github/workflows/superlinter.yml, CONTRIBUTING.md
Made additions to try to avoid missing making migrations.
none
- **NOTE, THIS PR IS A BRANCH OFF OF THE BRANCH FOR PR #24 (`msrun_protocol`)! (I changed the base branch so that you see the diff with msrun_protocol for review.)**
- I removed the `---`-delimited section at the top of the PR template because github does not remove it for submitters like it does for the issue templates.  But I left in a single `---` at the top to prevent markdownlint from throwing an MD041 error in the template (top level heading missing).
- I also tweaked the wordings in the checklist so there's never an `n/a` case.
- It's also notable that if you have any text past a link on a line (where the link characters make the line longer than 80 characters), it will throw an error.  But if the last thing on a line …
=> Migrations documentation and PR additions

CONTRIBUTING.md, DataRepo/templates/compound_list.html, DataRepo/templates/home.html, DataRepo/urls.py, DataRepo/views.py, TraceBase/urls.py
Copied home template to a compound_list template and changed the home template to be a list of table list-views.  Also changed the format of the list view from a UL to a table where each row is a record.  The purpose is to support multiple table views.
- Resolves #53
Note, I added a `__str__` method to the compound model and a conversion method, which was a part of my builtin exploration, but left them.  Create an issue to remove if this is redundant/unnecessary.
I fleshed out a few things in the contrib doc - stuff I'd had to google and didn't want to have to google again.  I know some people have these things memorized, but I find it really useful to have them explicitly in the doc.
=> Compound view refactor

DataRepo/utils.py
Loads the many-to-many study-to-animal relationships.
- Resolves #70
I decided to just record the relationship not matter what (if the animal or study were newly created, or not). According to the [docs](https://docs.djangoproject.com/en/dev/topics/db/examples/many_to_many/), "Adding a second time is OK, it will not duplicate the relation"
=> Loading study animal relationships

DataRepo/tests.py, DataRepo/utils.py
This is an investigation into the possibility of validation of the predicted/expected results of a command script.
- Resolves #71
setUp and test organization is still not fully understood (by me).  When I employed call_command in the setUp, they appeared to be  employed for every individual test (so full file loads of both compound and samples for every single test, which seems inefficient).  So perhaps a different strategy or organization could be tried? **NOTE**: now employing  [`setUpTestData`](https://docs.djangoproject.com/en/3.2/topics/testing/tools/#django.test.TestCase.setUpTestData)
=> Investigate call_command in test harness

DataRepo/compositeviews.py, DataRepo/forms.py
Add type hints where they were missing
=> Add typehints where missing

DataRepo/utils.py
Just indented all the animal updates beneath the created block. 
- Resolves #145
Describe any areas of concern that code reviewers should pay particular
attention to.  E.g. There are significant logic changes in function X.
=> Indent all animal updates within created block

DataRepo/management/commands/load_accucor_msruns.py
Added a format note YYYY-MM-DD
- Resolves #112
=> Added date format guidance to load_accucor_msruns

DataRepo/templates/DataRepo/search/results/fcirc.html
Fix a bug in the fcirc template
=> Fix bug in fcirc template

DataRepo/models.py, DataRepo/tests/test_models.py
When all PeakData records for a PeakGroup have zero corrected_abudance,
various calculations were raising exceptions.
- Resolves #263
=> Fix calculations when total_abunance is zero

DataRepo/views.py
Fix spelling error
- Resolves #293
=> Fix spelling error

.github/ISSUE_TEMPLATE/feature_request.md
I realized that the description of the `feature inspiration` section of the `feature request` issue template was unclear/misleading, because often, I have seen that there has been a lot of overlap between the feature description section and the feature inspiration section.  So I tried improving the description to distinguish it from the feature description section.
Let me know if there is a better wording that would make it clearer and reduce overlap with the feature description.
=> Improved the feature inspiration section description

DataRepo/tests/test_models.py
Remove some extraneous code from tests
Just found this while working on other things.
=> Remove extraneous code from tests

DataRepo/templates/upload.html
Simplify the study submission process by having the researchers add things to Google Drive themselves and simply point us to the Google Drive folder instead of attempting to have them submit the files via the form.
- Resolves #318
=> Update study submission process

DataRepo/templates/DataRepo/animal_detail.html
Changed exact to iexact
- Partially Resolves #339
Making this change on github because it's simple and my clone is in the middle of an edit.  The bug is in 2 other detail templates, so I will submit them individually.  I won't close #339 until I have implemented an error when an invalid ncmp value is supplied.
=> Basic search links fixed in animal detail

DataRepo/templates/upload.html, DataRepo/templates/validation_disabled.html, DataRepo/tests/test_views.py, DataRepo/urls.py, DataRepo/views.py
There is a bug in the validation code, temporarily disabling it while we
investigate.
Issue pending
=> Disable validation

.python-lint, DataRepo/example_data/small_dataset/small_obob_study_params.yaml, DataRepo/models.py, DataRepo/templates/base.html, DataRepo/templates/home.html, DataRepo/templates/includes/leaderboard.html, DataRepo/templates/includes/leaderboards.html, DataRepo/tests/test_models.py, DataRepo/utils.py, DataRepo/views.py
* Non-model class Researcher to encapsulate lookup logic
* Subtemplate to display the top researchers by number of studies,
number of animals, and number of PeakGroups
* Fix incorrect researcher name on small_obob_study_params loading
params
- Resolves #319
=> Add Data Submission Leaderboards

.github/workflows/superlinter.yml, .github/workflows/tracebase-tests.yml, DataRepo/example_data/small_dataset/small_obob_study_params.yaml, DataRepo/example_data/tissues/loading.yaml, DataRepo/schemas/load_study.yaml, requirements/dev.txt
super-linter updated some dependencies and YAML rules
This fixes some bad formatting in the YAML files in the repo
Also bumps the linter versions in `requirements/development.txt` to match the super-linter versions.
=> Cleanup YAML files

requirements/dev.txt
Update linter versions to match latest super linter
=> Update linter versions to match latest super linter

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
I find I'm constantly making these changes to issues I work on.  Mainly, it's the use of checkboxes for requirement and test tracking during implementation, but also some changes to help guide entry.
none
=> Quick/minor Issue template tweak

.github/ISSUE_TEMPLATE/feature_request.md
Added a "dependencies" section.
I also streamlined and clarified other portions of the template.
Adding a dependencies section will aid developers when searching for an issue to tackle.  Probably a label should be created too... I had the idea to add this section as I was looking through issues and discovered some issues could not be started, though it wasn't immediately clear from the text, as the issues were "linked" instead of tagged and did not show an icon of the issue status.
- I wrote these changes using the github interface. If the CI finds a problem, I'll address it
=> Added a "dependencies" section

.github/pull_request_template.md
Tried to make the test items in the PR template checklist clearer.
none
none
=> Improved the PR template checklist

.python-lint
There was an update to pylint that remote GH superlinter runs are using and generating errors.  Updates were made to eliminate those errors.
- Resolves #487
non
=> pylint updates for latest version.

README.md
Add status badges for GitHub actions to README.md
- Tests
=> Add GitHub actions status badges to README.md

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
The labels were recently revamped and the bug/enhancement labels changed.  They had to be updated in the templates.
none
- Tests
=> Updated the labels in the github issue templates.

DataRepo/templates/upload.html
Link to the new upload template.
- Resolves #544 
Describe any areas of concern that code reviewers should pay particular
attention to.  E.g. There are significant logic changes in function X.
- Tests
=> Use updated upload template

DataRepo/templates/navbar.html
Add a Help menu and link to the Google Drive folder where we are developing the help documentation.
- Resolves #540 
- Tests
=> Add Help menu link to Google Drive folder

changelog.md
See title
- Resolves #440
none
- Tests
=> Added a change log

.github/pull_request_template.md
Added an item to the PR checklist to update the `changelog.md` file.
None
=> Add changelog update to PR template checklist

DataRepo/templatetags/customtags.py, changelog.md
Added DataFrame changes to changelog before creating tag for release 2.0.1.
None
=> Update changelog for release 2.0.1

DataRepo/utils/exceptions.py
2 line change to error message - very simple.
- Resolves a todo item in a comment on issue #580
No notes.
- Will do upon merge/rebase
- Tests
=> Validation refinements informed by Cold Exposure data 3 - Added file context to error

DataRepo/management/commands/load_animals_and_samples.py, DataRepo/management/commands/load_study.py, DataRepo/management/commands/load_study_set.py, DataRepo/utils/exceptions.py, DataRepo/utils/sample_table_loader.py
Forgotten updates relating to `load_study_set`.  The exception raised by `load_study` changed and `load_study_set` was catching the old exception.  That had to be updated.  Then I realized a few other related issues that I made relatively quick fixes to.
- Resolves #580
I will add in-line review notes.
- All the changes are consistent with the changes previously described.  These were just forgotten edits that needed to be made
- Tests
=> Phase7 load study set updates

TraceBase/.env.example, TraceBase/settings.py
Django has a security setting ([`ALLOWED_HOSTS`](https://docs.djangoproject.com/en/4.2/ref/settings/#allowed-hosts)) that only allows selected hosts to be served by the site. In development this is typically `localhost`, however in production, this needs to be set to the hostname of the server. We had previously been appending the contents of the `HOST` variable, but this is not set on the tracebase servers. Instead, this PR uses a specific `ALLOWED_HOSTS` environment variable, allowing us to configure each system with env vars as we do for other settings.
This PR will be merged into `main` as well as cherry-picked into the `release_2.0.x` branch.
- …
=> Use ALLOWED_HOSTS env var

.github/ISSUE_TEMPLATE/new_release.md
Releasing a new version requires a number of steps. Having a checklist can help ensure the proper steps are followed.
More [detailed docs on the process are in NPLC Admin docs](https://nplcadmindocs.princeton.edu/index.php/TraceBase#New_Release). This template is meant to be an easy to read checklist of steps.
=> Add new release issue template

.github/pull_request_template.md
In order to make all to-do items not necessitate manual change in the most common cases (and to make it consistent in its intended usage (to be used by reviewers instead of the author) and thus assume everything has been done, I added "or no change" to the changelog checklist item, and streamlined the wording to keep the line under 80 characters.
None
=> Tweaked the changelog checklist item to reflect most common cases.

DataRepo/migrations/0025_alter_msrunsample_options_and_more.py
=> Changed migration file name and dependency

DataRepo/management/commands/export_studies.py, DataRepo/tests/test_studies_exporter.py, DataRepo/utils/studies_exporter.py
Add `--force` option to allow `export_studies` to overwrite existing files.
Write output to temp files first and move when complete to minimize time when files are incomplete.
- Resolves #__issue_number__
Resolves #808 
None
=> Issue 808 export studies force

DataRepo/management/commands/load_accucor_msruns.py, DataRepo/utils/file_utils.py, DataRepo/views/loading/validation.py
Follow-up to the review of PR #816.  Changes from a later PR were utilized to address the issues raised, thus this subsequent PR.
- Resolves issues from review of PR #816
- Merges into PR #831
None
=> Load msrun sample sequence 2

DataRepo/views/nav.py
Display card with count of peak annotation files on home page.
- Resolves #840 
=> Display card with count of peak annotation files

CONTRIBUTING.md
Update commands in CONTRIBUTING.md to use new loading options.
Use `load_tissues` command for consistency, instead of `load_study` command.
Update the flags for `load_accucor_msruns
=> Update commands in CONTRIBUTING.md to use new loading options

DataRepo/migrations/0034_alter_tissue_description.py
Simple fix
- Resolves failed tests in main (no issue)
Straightforward.  2 recent merged produced a migration file.
=> Migration conflict from merge - fix

CHANGELOG.md, DataRepo/tests/test_formats.py, requirements/common.txt
Added tests for the new `getModelFromInstance` function and updated the `CHANGELOG.md`
- Resolves #__issue_number__
=> Test getModelFromInstance, update CHANGELOG

DataRepo/tests/apps/test_apps.py, DataRepo/tests/utils/test_loader.py, DataRepo/utils/loader.py
I discovered that the new subdirectory in the tests directory wasn't getting any tests run, because I hadn't added `__init__.py`.  I had initially run those tests explicitly and they worked, but changes since then should have broken them, so when all the tests passed, I investigated and found the omission.  This PR represents a catch-up of the broken tests.
- Partially addresses #824
- Merges into #869
- Next PR: #871
- Associated issue/pull …
=> Sequence load 3 (missing test init)

DataRepo/tests/test_exceptions.py, DataRepo/utils/exceptions.py
Simple.
- Partially addresses #824
- Merges into #872
- Next PR: #874
=> Sequence load 6 (new exception class tests)

DataRepo/data/tests/load_table/defaults.csv, DataRepo/tests/utils/test_file_utils.py
Added tests for the new file_utils methods.
- Partially addresses #824
- Merges into #873
- Next PR: #875
=> Sequence load 7 (new file utils methods tests)

DataRepo/tests/utils/test_loader.py, DataRepo/utils/loader.py
Added tests for new TraceBaseLoader methods and fixed a couple issues they revealed.
Details:
- Added a check of existing column type definitions before checking that default values are of the correct type.
- Raised the exception about mssing required headers after having added the unknown headers error.
- Partially addresses #824
- Merges into #874
- Next PR: #876
- Overhead …
=> Sequence load 8 (loader method tests and fixes)

DataRepo/management/commands/load_compounds.py, DataRepo/management/commands/load_protocols.py, DataRepo/management/commands/load_sequences.py, DataRepo/management/commands/load_study_table.py, DataRepo/management/commands/load_table.py, DataRepo/management/commands/load_tissues.py, DataRepo/models/utilities.py, DataRepo/tests/management/test_load_table.py, DataRepo/tests/models/test_utilities.py, DataRepo/tests/utils/test_file_utils.py, DataRepo/tests/utils/test_table_loader.py, DataRepo/utils/__init__.py, DataRepo/utils/compounds_loader.py, DataRepo/utils/file_utils.py, DataRepo/utils/protocols_loader.py, DataRepo/utils/sequences_loader.py, DataRepo/utils/study_table_loader.py, DataRepo/utils/table_loader.py, DataRepo/utils/tissues_loader.py
Settled on better names for the abstract classes:
- `TraceBaseLoader` -> `TableLoader`
- `LoadFromTableCommand` -> `LoadTableCommand`
- Merges into #885
=> Renamed `TraceBaseLoader` and `LoadFromTableCommand`

TraceBase/.env.example, TraceBase/settings.py
Provides the ability to configure the archive directory using and environment variable
- Resolves #__issue_number__
- Partially addresses #732
=> Provide env var for archive directory

DataRepo/forms.py, DataRepo/templates/DataRepo/validate_submission.html, static/js/file_list_drop_area.js
Initial form:
Filled in:
Note, this did not update the upload instructions - just the interface.
Details:
- New title.
- Changed the order of the file fields (focussing on the peak annotation files)
- Reframed the animal/sample table as the "output file".
- Added a way to show what peak annotation files were selected.
- Removed the help text, as it is now unnecessary and intimidating.
- Added the ability to **add** files (to address browser issues Michael reported, associated with input files being in different directories).  And added a Clear button to allow the added files to be cleared.
- Merges into PR #925
- Next PR: #928
author and/or reviewers should …
=> Rebranded the validation interface

.github/workflows/superlinter.yml, .github/workflows/tracebase-tests.yml, CONTRIBUTING.md, DataRepo/formats/dataformat.py, DataRepo/loaders/accucor_data_loader.py, DataRepo/loaders/sample_table_loader.py, DataRepo/loaders/table_loader.py, DataRepo/management/commands/load_study.py, DataRepo/utils/exceptions.py, DataRepo/utils/file_utils.py, DataRepo/utils/lcms_metadata_parser.py, DataRepo/utils/queryset_to_pandas_dataframe.py, TraceBase/urls.py, TraceBaseDocs/TraceBaseDocs/Values/Example of Enrichment Fraction and Abundance Calculation.md, requirements/dev.txt
Update SuperLinter to version 6. See list of significant changes here: https://github.com/super-linter/super-linter/blob/main/docs/upgrade-guide.md
In addition to changing the super-linter version, this required the following:
* Add specific permissions to GitHub actions to restrict the permissions granted to `GITHUB_TOKEN`
* Some formatting changes dictated by updated versions of black, flake8, etc.
* One actual code change required was replacing direct comparisons of `type()` with the use of `isintance()`. See https://www.flake8rules.com/rules/E721.html.
- All blocking issues …
=> Superlinter black update

DataRepo/loaders/accucor_data_loader.py, DataRepo/templates/DataRepo/validate_submission.html, DataRepo/tests/test_views.py, DataRepo/tests/views/upload/test_validation.py, DataRepo/views/upload/validation.py, static/css/drop_area.css
This PR adds the ability to automatically detect if fixes to data (other than adding missing sample names) would be fruitful.  It is pointless to validate the data for the detection and repair (or reporting of issues that need attention) if the user has not yet fleshed their data out, manually.  This enables us to skip the full processing of the files by shortcutting to handling only the extraction of data supported for autofill (which is currently: sample names).
This code results in the processing of the largest study (cold exposure) to only take a handful of seconds.
- Minimum …
=> Autofill only mode

.gitignore, DataRepo/templates/upload.html, DataRepo/views/upload/submission.py, DataRepo/views/upload/validation.py, TraceBase/settings.py, static/css/file_tree.css
- Added drive details to the settings
- Added a file tree css file for displaying a directory structure
- Added some fast tooltips
=> Updated the upload page for the updated submission process

DataRepo/templates/upload.html, DataRepo/views/upload/submission.py, TraceBase/.env.example, TraceBase/settings.py, static/css/file_tree.css
Note that I also updated the submission google form (already live).
- Changed the submission doc link (in the example env file) - **Note, this will need to be changed in the `.env` file after deployment.**
- Changed the settings to get the submission details from the env file
- Fixed the upload page background (light gray to white)
- Fixed the expand/collapse icon updates
- Resolves #941
- Resolves #943
- Resolves #944
- Partially addressed #939 (links to a wiki page on the repo stating that the docs are under renovation)
- All blocking issues resolved by …
=> Fixed minor bugs on the submission/upload page

DataRepo/loaders/sample_table_loader.py
Resolves #951
Use the correct `rownum` variable to report which row a missing tissue record is on. 
Also, update the `rownum+2` to be `rownum+1` which seems to report the correct row number.
- Resolves #951 
=> Fixes missing tissue error reporting

DataRepo/fixtures/data_formats.yaml
Note: This will require reloading of the DataFormat fixture to running instances
Adds the Iso-Autocorr format to the DataFormat fixtures.
- Resolves #955
=> Add Iso-Autocorr DataFormat to fixtures

DataRepo/utils/exceptions.py
Addressed review issues.
- Added a docstring with an example usage.
- Added a comment inside the conditional that appends to the supplied message.
- Removed "majic number".
- Streamlined a bit.
I have not switched from placeholders to f-strings, but only because I want to move on to the next effort.  If you would like to still see that change, I'll create an issue.
- Merges into PR #901
- Associated issue/pull request …
=> `InfileError` improvements

DataRepo/models/animal.py, DataRepo/models/peak_group_label.py
Trivial comment fixes.  Most appear to be copy-paste-o's.
I was reviewing all of the calculation methods, looking for problems with respect to multiple peak group representations of the same compound, and while doing that, I encountered mistakes in the comments/docstrings that I fixed as I went.
=> Trivial comment fixes

DataRepo/loaders/table_loader.py
Note, this is implemented in another branch, but I did it here just because we needed it.
Only tested manually with:
```
python manage.py load_msruns --mzxml-files blah.mzXML --operator "MichaelNienast" --date 2024-05-30 --lc-protocol-name polar-HILIC-25-min --instrument QE
```
- (temporarily) Resolves #977
=> Added rownum to `TableLoader.__init__`

DataRepo/tests/tracebase_test_case.py, TraceBase/runner.py, TraceBase/settings.py
I made these changes after implementing the code that cleans up upon either explicit ArchiveFile delete or rollback in the MSRunsLoader, but this code can be used without those features to test ArchiveFile creation.
To be able to test actual file existence and the cleanup of the archive directory, I tweaked the settings to make it easier to use `override_settings` decorators to be able to test actual file creation/deletion.  I added a TraceBasetestCase class for the cleanup code.  It can be used for actually testing file creations/deletions
You cannot set a settings dict key value in a settings override, so creating separate settings variables to be able to change makes it more straightforward.  This in controlled in the superclass mentioned above that comes with builtin cleanup.
- …
=> Improvements to settings for testing the archive directory.

DataRepo/loaders/msruns_loader.py
... and added a call to delete_all_caches.
This should have been done before.  In fact, this should also employ a `MaintainedModel.defer_updates` decorator.  Neither are necessary.  The code works with or without it.  It's just a question of speed.
This could also be more nuanced.  E.g. No need to delete caches if nothing was created, but there is a current need for this functionality.  We can improve it later.  And we can apply deferred autoupdates later too.
- Resolves no isue
- Specific reviewers: …
=> Disabled caching updates in the msruns loader

requirements/common.txt
A `numpy` update broke `chempy` awhile back, which made the tests in main start failing.  I had fixed this in a branch in PR #1005 by pinning the version to just before the update, but in order to create a release off main (#1074), that saves main before the merge of the largely unreviewed submission and load updates PR series, I decided I would cherry pick just the `requirements/common.txt` file from that branch with:
```
git restore --source 5f1d858 -- requirements/common.txt
```
- Resolves [chempy/issues/234](https://github.com/bjodah/chempy/issues/234)
- Related to #1074
Just for documentation's sake, here are the commands I used to find the branch/hash where the numpy pin change was:
```
$ git checkout cherries_backward_compatibility
$ git grep numpy `git rev-list --all` -- …
```
=> Cherry-picked the requirements/common.txt file from the branch in PR 1005 to fix main

DataRepo/loaders/base/table_column.py, DataRepo/loaders/base/table_loader.py, DataRepo/loaders/infusates_loader.py, DataRepo/loaders/msruns_loader.py, DataRepo/loaders/sequences_loader.py, DataRepo/loaders/study_loader.py, DataRepo/loaders/tracers_loader.py, DataRepo/views/upload/validation.py
- Merges into PR #1036
- Next PR: #1055
=> Added color to exported study doc

DataRepo/management/commands/load_study.py
This replaces the old `load_study` with the new.  I'd wanted to catch when the old args were used and do a `call_command` on the legacy version, but I googled before attempting and wasn't sure that would work, so I didn't spend time on it.
I forgot to mention that I did this for the old `load_samples.py` script (because I'd renamed the replacement script for that one in the previous PR).
I didn't add tests.  I'll do that after I accomplish the backwards compatibility issue (#1032).
- Resolves #1041
- Merges into: #1058
- Next PR: #1064
- All blocking issues …
=> New `load_study.py` script

DataRepo/loaders/legacy/accucor_data_loader.py, DataRepo/loaders/msruns_loader.py, DataRepo/loaders/peak_annotations_loader.py, DataRepo/loaders/samples_loader.py, DataRepo/loaders/sequences_loader.py, DataRepo/tests/loaders/test_samples_loader.py, DataRepo/tests/loaders/test_study_loader.py, DataRepo/tests/loaders/test_tracers_loader.py, DataRepo/tests/management/commands/legacy/test_load_accucor_msruns.py, DataRepo/tests/management/commands/test_load_lcms_metadata.py, DataRepo/tests/management/commands/test_load_samples.py, DataRepo/tests/management/commands/test_load_study.py, DataRepo/tests/utils/test_exceptions.py, DataRepo/tests/views/upload/test_validation.py, DataRepo/utils/exceptions.py, DataRepo/utils/file_utils.py, DataRepo/utils/text_utils.py
Fixed a couple bugs related to date strings and numbers.
- Partially addresses #1032
- Partially addresses #1041
- Partially addresses #1048
- Partially addresses #839
- Partially addresses #1062
- Merges into PR #1065
- Next PR: #1068
=> `V3 Loading PR Series #4`: Date string and number string fixes

DataRepo/forms.py
Removed accucor and isocorr validation from the submission form.
Added a check that each peak annotation file is excel, csv, or tsv.
- Resolves #1043
- Merges into PR #1080
- Next PR: #1082
=> Allow csv, tsv, and isoautocorr on the submission page

DataRepo/management/commands/profile_submission_page.py, DataRepo/views/upload/validation.py
Added a script to profile the submission page performance in order to inform efforts to make it faster.  When I was testing these files:
- [col013a_negative_cor.xlsx](https://github.com/user-attachments/files/16480728/col013a_negative_cor.xlsx)
- [col013a_pos-highmz_cor.xlsx](https://github.com/user-attachments/files/16480730/col013a_pos-highmz_cor.xlsx)
I noted that it was taking just over a minute, which encounters a gateway timeout on dev.  I fix the performance in the next PR so that this is no longer an issue, but this PR just is for the profiling command I added which I used to diagnose the performance issue, and which will likely come in handy again later for the validation phase and loading in general.
I also made a minor modification to the `DataValidationView` class to make it …
=> Added a script to profile the submission page performance

DataRepo/templates/upload.html, TraceBase/.env.example
- Resolves #1050
- Merges into PR #1085
- Next PR: #1129
=> Updated the upload template for processing the v3 study doc.

DataRepo/templates/DataRepo/validate_submission.html, DataRepo/views/upload/validation.py, static/css/tabbar.css
This ONLY adds the tab-bar.  The tabs are clickable to change pages, but this PR is mainly for aesthetics and CSS review.
Details:
- Added a CSS file for the customized css based on the bootstrap code.
- Added DataValidationView.get_context_data to be able to pass the page as a URL parameter.
- Added HTML to the submission template.
Screenshot:
Much of this work was informed by the following documentation:
https://getbootstrap.com/docs/4.1/components/navs/
- Partially addresses #1093
- Merges into PR #1113
- Next PR: #1134
- All blocking issues resolved by …
=> Added a tab-bar to the submission page

static/css/tabbar.css
I found it rather annoying that the "tabs" would "soft wrap" in kind of an ugly fashion, so I changed the behavior such that they now "squeeze" based on the window width, and all stay on one line.
Removed unused css and addressed tab-bar width behavior wo avoid element wrapping.
The "tabs" are all the same width now (instead of them being relative to the content of their text) and the "padding" is essentially governed by the size of the parent container.
Before this change, narrowing the window would look like this:
After, it looks like this (just WRT the tab bar - this screenshot includes changes in the next PR):
- Partially addresses #1093 (even though the PR this merges into "resolves" it - just a tweak)
- Merges into PR #1135
- Next PR: #1137
This pull request …
=> Submission tab-bar width behavior tweak

DataRepo/templates/submission/includes/1_start.html, DataRepo/views/upload/submission.py
Updated the submission start page.
Details:
- Hid the next button unless there are results.
- Hid the study doc field.
- Changed the page wording to match the last template design.
- Added a state variable to the template context and used it to color the next button to represent success, warning, or failure.
- Resolves #1121
- Merges into PR #1136
- Next PR: #1138
- Overhead …
=> Submission start page

DataRepo/templates/submission/includes/2_fill_in.html, DataRepo/templates/submission/submission.html, static/js/submission_fillin.js
Fleshed the fill-in page and added a next button.
Details:
- Added css and javascript to submission.html.  (I wanted to add it to the included template, but could not figure out how to do that.)
- Put all the javascript into submission_fillin.js
- Copied the instructions from upload.html and edited them for brevity.
- Resolves #1122
- Merges into PR #1137
- Next PR: #1139
- Overhead …
=> Submission Fill In page

DataRepo/forms.py, DataRepo/templates/submission/includes/1_start.html, DataRepo/templates/submission/includes/2_fill_in.html, DataRepo/templates/submission/includes/3_validate.html, DataRepo/templates/submission/submission.html, DataRepo/views/upload/submission.py
Got the validate tab of the submission form working.
Details:
- Added a "mode" form field that can be either validate or autofill.  It is hidden and based on the active tab.
- Added conversion of the URL parameters to initial form mode field values.
- Edited the included css and javascript headers based on the active tab.
- Hid the peak annotations input.
- Eliminated the "expand" control for the status report.
- Fixed the "Next" button on the fill-in and validate tab pages.  (They were all going to "Fill In".)
- Resolves #1123
- Resolves #1125
- Merges into PR #1138
- Next PR: #1149
- Minimum approvals: 1 …
=> Submission validate page

DataRepo/templates/submission/includes/4_submit.html, DataRepo/templates/submission/submission.html, DataRepo/views/upload/submission.py, TraceBase/.env.example
Updated the submit page for the submission view.
Details:
- Changed the way the `SUBMISSION_DRIVE_DOC_URL` environment variable is used and added a comment that it expects the page location to be appended to it.
- Added the submission environment variables to the context when rendering the submit page.
- Added a footer to the submission template.
- Copied the last step from the upload.html template to the 4_submit.html template and edited it.
- Resolves #1124
- Merges into PR #1139
- Next PR: #1141
- Specific …
=> Submission submit page

DataRepo/templates/submission/includes/1_start.html, DataRepo/templates/submission/includes/3_validate.html, static/js/submission.js
Details:
- Created a span element in 1_start.html and 3_validate.html to save the output file name.
- Updated submission.js to retrieve the output file name from the new span element.
- Resolves #1144
- Merges into PR #1143
=> Fixed the downloaded filename from the submission forms

DataRepo/loaders/infusates_loader.py, DataRepo/loaders/tracers_loader.py, DataRepo/utils/infusate_name_parser.py
Addressed infusate/tracer consistency check issue associated with spaces between isotopes.
Added in a case consideration while I was at it.
Incidentally, I had initially branched this off main, but was unable to test it due to unfixed issues on main, so I branched off the latest branch.
- Resolves #950
- Merges into PR #1145
- Next PR: #1152
=> Fixed the consideration for spaces existing between isotopes in multi-label tracers

DataRepo/models/peak_data.py
=> Edited the fraction method's docstring for accuracy.

DataRepo/templates/DataRepo/archive_file_list.html, DataRepo/templates/DataRepo/compound_list.html, DataRepo/templates/DataRepo/includes/animal_list_stats_table.html, DataRepo/templates/DataRepo/includes/animal_sample_msrun_table.html, DataRepo/templates/DataRepo/includes/lcmethod_table.html, DataRepo/templates/DataRepo/includes/protocol_table.html, DataRepo/templates/DataRepo/includes/study_animal_sample_msrun_table.html, DataRepo/templates/DataRepo/includes/study_animal_sample_msrun_table_detailpage.html, DataRepo/templates/DataRepo/includes/study_list_stats_table.html, DataRepo/templates/DataRepo/tissue_list.html
I just closed 2 other PRs that were a more involved fix for this issue.  Each has its pros and cons, but this fix was just setting a single attribute in the table definition based on another [bs-table issue](https://github.com/wenzhixin/bootstrap-table/issues/421) I googled and found.  That issue had a [comment](https://github.com/wenzhixin/bootstrap-table/issues/421#issuecomment-479603606) with an alternate fix compared to the one I'd found before, which required server-side pagination.
- Resolves #1038
- All blocking issues resolved by …
=> Small fix for the 200 row bootstrap table download limit

DataRepo/models/msrun_sample.py, DataRepo/templates/DataRepo/peakgroup_detail.html, DataRepo/templates/DataRepo/peakgroup_list.html
Also changed the `__str__` method in `MSRunSample` to shorten it, because it was way too long.
Before this change:
- Resolves no recorded issue
=> Fixed empty MSRun names in the peak group templates

DataRepo/templates/DataRepo/includes/animal_list_stats_table.html, DataRepo/templates/DataRepo/includes/animal_sample_msrun_table.html, DataRepo/templates/DataRepo/includes/study_animal_sample_msrun_table.html, DataRepo/templates/DataRepo/includes/study_animal_sample_msrun_table_detailpage.html, DataRepo/templates/DataRepo/includes/study_list_stats_table.html
Basically, I just removed the classes defining a minimum and maxomum percentage width, e.g.: '<th class="min-vw-3 max-vw-10" ...'.
- Resolves #984
=> Fixed all of the column overrun issues in the templates

DataRepo/templates/submission/includes/3_validate.html
Tried to clarify that the validate page downloads a copy of the study doc with fixes.
- Resolves #1172
=> Clarifications to the validation process

DataRepo/loaders/msruns_loader.py, DataRepo/models/msrun_sequence.py, DataRepo/utils/exceptions.py
Added context to this error for users:
Fixed this error:
To read as:
=> Added a catch to explain a sequence name parsing-related error

TraceBaseDocs/TraceBaseDocs/Upload/How to Upload.md
I also added a note to the nplcadmindocs (because it took me a long time to find where and how to deploy the documentation changes).
And I deployed the changes to github.
- Resolves #939
=> Updated the upload instructions in the docs.

DataRepo/templates/DataRepo/includes/animal_list_stats_table.html, DataRepo/templates/DataRepo/includes/animal_sample_msrun_table.html, DataRepo/templates/DataRepo/includes/study_animal_sample_msrun_table.html, DataRepo/templates/DataRepo/includes/study_animal_sample_msrun_table_detailpage.html, DataRepo/templates/DataRepo/includes/study_list_stats_table.html, DataRepo/templates/DataRepo/infusate_list.html, DataRepo/tests/utils/test_queryset_to_pandas_dataframe.py, DataRepo/utils/queryset_to_pandas_dataframe.py
As discussed in the developer's meeting on 8/19/2024.  Michael suggested these changes and I confirmed with Fan over slack.
- Resolves #1168
=> Clarified "labeled elements" to represent combinations of elements among the tracers in the infusates

DataRepo/forms.py, DataRepo/templates/submission/includes/1_start.html, DataRepo/templates/submission/includes/3_validate.html, DataRepo/templates/submission/submission.html, DataRepo/views/upload/submission.py, static/js/submission_start.js
...by converting the 1 form to a formset.
- Resolves #1221
- Merges into PR #1234
=> Got the validate page working again

DataRepo/loaders/msruns_loader.py, DataRepo/loaders/study_loader.py, DataRepo/management/commands/load_msruns.py, DataRepo/management/commands/load_study.py, DataRepo/tests/loaders/test_msruns_loader.py, DataRepo/tests/loaders/test_study_loader.py
- Resolves #893
- Resolves #1086
- Merges into PR #1239
=> Added `--mzxml-dir` option to load_study and load_msruns

DataRepo/loaders/msruns_loader.py, DataRepo/tests/loaders/test_msruns_loader.py
- Resolves #1241
- Merges into PR #1246
=> Made the `Peak Annotation Details` sheet's `Sequence` column optional when the row is marked to be skipped

DataRepo/loaders/legacy/accucor_data_loader.py, DataRepo/loaders/peak_annotations_loader.py, DataRepo/management/commands/legacy_load_accucor_msruns.py, DataRepo/tests/loaders/test_peak_annotations_loader.py
Michael noted that the corrected abundance values were wrong.  See the issue for details.
- Resolves #1250
- Merges into PR #1247
=> Fixed a copy-paste-o where RAW should have been CORRECTED

DataRepo/formats/dataformat.py, DataRepo/formats/dataformat_group_query.py, DataRepo/formats/peakgroups_dataformat.py, DataRepo/templates/DataRepo/search/results/peakgroups.html, DataRepo/templatetags/customtags.py, DataRepo/tests/test_formats.py
- Partially addresses #1262 (still need to do the peakdata format)
=> Show mzXML files in the peak group advanced search results

DataRepo/forms.py
=> Fixed an exception that occurs when a csv or tsv file is submitted on the submission start page

DataRepo/views/upload/submission.py
Formats for `isocorr` and `isoautocorr` are sufficiently equivalent for autofill extraction when a csv file is submitted, so this PR adds the ability to extract autofill from a csv file when the matching format is a list of those 2 formats.
Details:
- Added instance variable 'files_with_format_errors' to the BuildSubmissionView to be able to track peak annotation files whose format detection was ambiguous.
- Added a warning when a peak annotation file was narrowed down to either isocorr or isoautocorr and arbitrarily selected isocorr when a csv or tsv is submitted in order to perform the autofill extraction.
- Added the ability to not autofill the file format in the peak annotation files sheet when there was an error in the format determination.
- Resolves #1291
- Merges into PR #1290
See …
=> Added the ability to extract autofill when file format cannot be determined

DataRepo/loaders/peak_annotations_loader.py, DataRepo/loaders/study_loader.py, DataRepo/models/peak_group.py, DataRepo/tests/management/commands/legacy/test_load_accucor_msruns.py, DataRepo/utils/exceptions.py
=> Updated the suggested resolution in the various multiple representation exceptions

DataRepo/loaders/msruns_loader.py, DataRepo/utils/exceptions.py
This fix was needed to be able to load study `lingfan_albko_fcirc_2022-08`.  The changes are simple, so I am not requesting review, but I am fleshing out the description here for documentation purposes.
- Exception classes created:
- PossibleDuplicateSamples
- PossibleDuplicateSamplesError (to summarize PossibleDuplicateSamples exceptions)
- SummarizedInfileError (to aid in summarizing a list of exceptions derived from InfileError)
- Moved SummarizableError to co-locate it with SummarizedInfileError
- Buffered PossibleDuplicateSamples as a warning in the MSRunsLoader.
Before this PR:
After the PR:
- Resolves #1313
- Merges into PR #1310
author and/or reviewers should uncheck any unmet …
=> Created a `PossibleDuplicateSamples` exception class to to be buffered as a warning

DataRepo/loaders/peak_annotations_loader.py
- Resolves #1320
- Merges into PR #1321
=> AccuCor `C_Label` error Fix

DataRepo/tests/utils/test_exceptions.py, DataRepo/utils/exceptions.py
I started writing a bunch of tests because I was worried about some recent changes that I thought needed a bit more rigor.  I'm checking in files for separate PRs.  This is the low hanging fruit.
- Merges into PR #1322
=> Added some exception tests

DataRepo/loaders/base/converted_table_loader.py, DataRepo/tests/loaders/base/test_converted_table_loader.py
See in-line comments.
- Resolves no documented issue - just some test catch-up for previously implemented issues
- Merges into PR #1323
=> `ConvertedTableLoader` minor bug fixes

DataRepo/tests/loaders/base/test_table_loader.py, DataRepo/utils/file_utils.py
See in-line comments.
- Resolves no documented issue (just catching up on testing)
- Merges into PR #1324
=> Added `TableLoader` tests

DataRepo/loaders/peak_annotations_loader.py, DataRepo/tests/loaders/test_peak_annotations_loader.py
- Resolves no documented issue - just catching up on tests
- Merges into PR #1325
=> C12 PARENT first row fix

DataRepo/tests/views/search/test_download.py
- Resolves no recorded issue - just catching up on testing
- Merges into PR #1326
=> More download tests

DataRepo/forms.py, DataRepo/templates/DataRepo/search/query.html, DataRepo/templates/DataRepo/search/results/display.html, DataRepo/urls.py, DataRepo/views/__init__.py, DataRepo/views/search/__init__.py, DataRepo/views/search/advanced.py, DataRepo/views/search/basic.py, DataRepo/views/search/download.py
Apparently, I neglected to create a PR for this branch that implements the mzXML download button on the advanced search page.
- Resolves #1261
=> Mzxml zip download button

DataRepo/loaders/base/converted_table_loader.py
=> Fixed a bug where missing formulas in accucor files were being called missing parent row errors

DataRepo/loaders/peak_annotations_loader.py
I made various other csv-related accucor loading fixes, but I had not tried the load using an unmerged corrected accucor sheet until today.  It causes the exception [seen in the fluxomics data](https://github.com/PrincetonUniversity/tracebase-rabinowitz-data/issues/173).
After this PR, I tried a dry-run load of one of the erroneous accucor csv files in the fluxomics study, and it succeeded:
- Partially addresses [rabinowitz data repo issue #173](https://github.com/PrincetonUniversity/tracebase-rabinowitz-data/issues/173)
- All blocking …
=> Fixed a bug that prevented loading of an unmerged accucor corrected sheet in csv format

DataRepo/utils/exceptions.py
=> Fixed `RuntimeError` associated with exception summarization

DataRepo/loaders/__init__.py, DataRepo/loaders/study_loader.py, DataRepo/management/commands/load_study.py, DataRepo/tests/loaders/test_study_loader.py, DataRepo/views/upload/submission.py
This is intended to be used by the github test action in the rabinowitz data repo to dramatically cut down on test time by skipping the Peak Annotation Files sheet.
Details:
- Checked the `StudyLoader.get_loader_class` method name to `get_derived_class` to not conflate it with the contained loader classes.
- Added argument `--exclude-sheets` to `load_study`
- Added class method: `get_loader_classes` to `StudyLoader`.
- Added method `check_exclude_sheets` to `StudyLoader`.
- Added `exclude_sheets` to the instance and skipped loaders with a `DataSheetName` that matches a name in that list.
- Resolves #1352
- …
=> Added the ability to skip sheet loads

DataRepo/context_processors.py, DataRepo/templates/navbar.html, TraceBase/.env.example, TraceBase/settings.py
Added an environment variable (READONLY) that controls whether the site is public or not (i.e. whether it accepts uploads and has the ability to edit data).
Details:
- Renamed the context processor method from debug to "globals" and made it return the value of the READONLY global variable from the settings.
- Added a READONLY global variable that defaults to False.
- Updated the `.env.example` file to include the READONLY variable.
- Updated the navbar template to not render the Upload and Admon links/buttons.
Before:
After:
- Resolves #1334 …
=> Added the ability to disable the upload page (for the public instance)

DataRepo/loaders/msruns_loader.py, DataRepo/utils/exceptions.py
This work changes this really long summary exception with repeated redundant file references:
to this succinct version (when all samples from given peak annotation files are missing):
It also made a change to the file associated with an exception in the non-succinct version to be the corresponding mzXML file instead of the study doc in cases where there are unexpected samples unaccounted for in the peak annotation details sheet (that were derived from the file name).
- Resolves #1403
- Resolves #1404
- All blocking issues resolved by …
=> Reformat allmissingsamples

DataRepo/data/tests/small_obob2/sample_table_headers_v3.yaml, DataRepo/data/tests/small_obob2/serum_lactate_sample_table_han_solo_v3.tsv, DataRepo/management/commands/load_samples.py, DataRepo/tests/management/commands/test_load_samples.py, DataRepo/utils/file_utils.py
Converted calls to legacy loaders in test_load_samples. 
Details:
- Fixed docstring in file_utils
- Included a test of the headers option provided by the superclass defined in load_table.py
- Added a check of options["animal_and_sample_table_filename"] in load_samples.
- Created v3 copies of some files under DataRepo/data/tests
- Corrected the docstring in load_samples.py
- Replaced call of legacy_load_samples and legacy_load_study in test_load_samples.py
- Partially addresses #1148
- Merges into PR #1412
- Specific …
=> Batch 9 of legacy loader test updates (`test_load_samples.py`)

DataRepo/tests/tracebase_test_case.py, TraceBase/.env.example, TraceBase/settings.py
Created settings for security settings recommended in the [django documentation](https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/).
This will necessitate another point release for pub.
- Partially addresses #1335
=> Security settings improvements

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/new_release.md, .github/pull_request_template.md
- Tried to make things more succinct
- Removed the migrations item, because the tests now check migrations are created
- Defaulted the changelog item to unchecked, sinc ethat seems to be the norm
- Added labels
- Put comments in less obtrusive places
- Added more examples
- Explained the why/what/how sections better
=> Issue and PR template tweaks

DataRepo/tests/test_views.py
- The number of tissues and compounds in the study file I switched to were different.
- There are 2 mzXML files that now load that weren't loaded before, so I had to split the expected sample count to a sample and msrun sample count.
- I had to modify queries to specify placeholder msrun sample records to avoid multiple records returned errors.
- Partially addresses #1148
- Basic …
=> Removed legacy loader calls from `test_views.py`

DataRepo/tests/views/search/test_download.py
Tests don't run if `__init__.py` files are missing.  Once added, there were some broken tests that had gone stale that I fixed.
None
=> Added missing init files and fixed omitted/stale tests

DataRepo/loaders/peak_annotations_loader.py, DataRepo/tests/loaders/test_peak_annotations_loader.py
Also corrected a comment that described the opposite of what the code below it was doing.
- Resolves #1453
=> Make the UnexpectedSamples exception a warning if all unexpected samples are skipped

TraceBase/settings.py
There is apparently no complete/perfect solution to this problem based on my current understanding.  Even if we didn't use the same loading code, **ANY** query to the DB will hang if a concurrent transaction modified anything that the validation does a query, update, or insert on.  The only solution would be to check data against itself and against other files (e.g. a consolidated compound file), and we would have to write all the error catching that the database does for us automatically.
This change to `SERIALIZABLE` seems to work *better* than `REPEATABLE_READ` because it didn't hang in an instance where the identical condition hung under `REPEATABLE_READ`.  It still hangs in other tests I tried (validating the same file that is loading in the background - which could mean that …
=> Changed the isolation level to `SERIALIZABLE`

DataRepo/models/maintained_model.py
Performance was improved as a side-effect of this change, by not saving propagated changes, which causes cache updates (which are the slow part).
Details:
- Improved the autoupdate message to differentiate between changed and unchanged values.
- Prevented change propagation if the source of the save trigger was a select (i.e. from `from_db`), as indicated by the via_query parameter.
- Some linting fixes were also included.
- Specific reviewers: …
=> Made lazy autoupdates lazier, improving performance

DataRepo/formats/dataformat.py, DataRepo/formats/dataformat_group_query.py, DataRepo/forms.py, DataRepo/templates/DataRepo/search/query.html, DataRepo/templates/DataRepo/search/results/display.html, DataRepo/templates/base.html, DataRepo/templates/sidebar.html, DataRepo/views/search/download.py, DataRepo/views/utils.py, DataRepo/widgets.py, static/js/cookies.js, static/js/submission_fillin.js
Details:
- Moved the javascript cookie methods into their own file and updated the script includes in the base template.
- Moved widget classes from forms.py into widgets.
- Moved Echo and ZipBuffer classes into the view utils.
- Clarified some random documentation and fixed some typos.
=> BST3: Code reorganization and documentation improvements

DataRepo/models/utilities.py, DataRepo/tests/models/test_utilities.py
Model utilities for the BST List View.
=> Bst7 model utilities

DataRepo/templatetags/customtags.py, DataRepo/tests/templatetags/test_customtags.py, DataRepo/tests/views/test_utils.py, DataRepo/views/utils.py
Added template tags and a graceful paginator for use in the BST list view/template.
=> Bst8 template tags

DataRepo/tests/tracebase_test_case.py
This allows derived classes to have their superclass methods get highlighted correctly and allows VSCode Intellisense to provide autocomplete suggestions.  There is no functionality change to tracebase.  This only eases development efforts.
Details:
- Created a TypeVar used in the factory method's type input and output
- Fixed the type hints of `Tracebase[Transaction]TestCase` from object instances to class types.
Differences to note in VSCode:
- Derived test class instances (i.e. "`self`" in instance methods) will now suggest methods and variables after typing a dot after `self`.
- All `TestCase.assert*` methods will be correctly syntax highlighted yellow instead of white
This pull request will be merged …
=> Improved the type hinting for the test case class factory

requirements/dev.txt
...  that allows pylint to be more compatible with django, specifically when running it on the command line.
=> Added a package to the dev requirements

TraceBase/settings.py, TraceBase/urls.py, requirements/dev.txt
This will aid in the BSTListView development and any other performance issues.
Docs: https://django-debug-toolbar.readthedocs.io/en/latest/installation.html
Once installed, if running in DEBUG mode, you see a sidebar on the site like this:
- Partially addresses #1476
=> Added the django debug toolbar as a dev dependency

TraceBase/.env.example, TraceBase/settings.py
Added `SECURE_HSTS_INCLUDE_SUBDOMAINS` and `SECURE_HSTS_PRELOAD` and improved comments on related security settings.
- Resolves #1452
=> Added security settings

DataRepo/tests/views/upload/test_submission.py
Trivial
- Partially addresses #1477
- Merges into branch `assert_not_warns_fixes`
- Previous PR #1486
- Next PR #1488
=> Deleted some debug prints in the submission interface tests

DataRepo/tests/views/upload/test_submission.py, DataRepo/views/upload/submission.py
This PR will change the internal server 500 error to be Http 403 error (Access Forbidden) if the public site revealed an attempt to access the disabled submission.
- Resolves #1480
This PR will use the `PermissionDenied` exception from Django to handle Http 403 access forbidden errors according to the following documentation:
https://docs.djangoproject.com/en/5.1/ref/views/#the-403-http-forbidden-view
I think it should be tested on the public site once the changes are updated on the server. 
I believe `settings.READONLY` environment variable is set to `TRUE` on the server.
- All …
=> Adding the 403 forbidden error instead of 500 error

DataRepo/loaders/base/table_loader.py, DataRepo/loaders/msruns_loader.py, DataRepo/loaders/peak_annotation_files_loader.py, DataRepo/loaders/peak_annotations_loader.py, DataRepo/loaders/study_loader.py, DataRepo/tests/loaders/test_msruns_loader.py, DataRepo/tests/loaders/test_study_loader.py, DataRepo/tests/management/commands/test_load_peak_annotation_files.py, DataRepo/tests/management/commands/test_load_peak_annotations.py, DataRepo/tests/utils/test_exceptions.py, DataRepo/tests/utils/test_infusate_parser.py, DataRepo/tests/views/upload/test_submission.py, DataRepo/utils/exceptions.py, DataRepo/utils/infusate_name_parser.py
This is a work in progress.
- Resolves #1527
=> Cryptic MissingSample Errors

DataRepo/utils/infusate_name_parser.py, DataRepo/views/upload/submission.py
This PR will wrap the error raised using a try except block to a avoid 500 server errors.
- Resolves #1514 
The `submission.py` file was modified to add the try-except block to handle the exception `IsotopeParsingError` raised by  the function `parse_isotope_string` .  
- Specific reviewers: @hepcat72  
=> Parsing Isotope Error

DataRepo/loaders/msruns_loader.py
=> Only abort an `MSRunsLoader` load when the missing samples don't appear to be blanks

DataRepo/loaders/animals_loader.py, DataRepo/loaders/samples_loader.py, DataRepo/tests/loaders/test_animals_loader.py, DataRepo/tests/management/commands/test_load_animals.py, DataRepo/tests/utils/test_exceptions.py, DataRepo/utils/exceptions.py
=> Missing FCirc Value Warning

DataRepo/static/js/bst/cookies.js, DataRepo/tests/static/js/bst/test_cookies.js, DataRepo/tests/static/js/tests.html, DataRepo/tests/views/models/bst/test_client_interface.py, DataRepo/views/models/bst/client_interface.py, static/js/cookies.js
Added view and column cookie javascript functions.
- Resolves #1565
- Merges into branch `bstlv7_column_select_list`
Javascript test run:
=> `BSTListView` 8: Javascript Cookies

DataRepo/tests/views/search/test_download.py, DataRepo/views/search/download.py
The real fix is an httpd.conf update I created a [ticket](https://nplc-helpdesk.princeton.edu/Ticket/Display.html?id=112583) for.  But, before I realized that, I attempted a fix thinking it was a speed issue.  This PR dramatically improves the mzXML download speed.  Still takes awhile, but it probably halves the time.
- Partially addresses #1587
- Overhead …
=> mzXML download speed improvement

DataRepo/models/utilities.py, DataRepo/static/js/bst/list_view.js, DataRepo/static/js/bst/paginator.js, DataRepo/templates/models/bst/list_view.html, DataRepo/templates/models/bst/paginator.html, DataRepo/templates/models/bst/scripts.html, DataRepo/templates/widgets/bst/rowsperpage_select.html, DataRepo/templates/widgets/bst/rowsperpage_select_option.html, DataRepo/tests/models/test_utilities.py, DataRepo/tests/static/js/bst/test_list_view.js, DataRepo/tests/static/js/bst/test_paginator.js, DataRepo/tests/static/js/tests.html, DataRepo/tests/templates/models/bst/test_list_view.py, DataRepo/tests/templates/models/bst/test_paginator.py, DataRepo/tests/views/models/bst/test_base.py, DataRepo/tests/views/models/bst/test_client_interface.py, DataRepo/tests/views/models/bst/test_list_view.py, DataRepo/tests/views/models/bst/test_utils.py, DataRepo/tests/widgets/bst/test_rows_per_page_select.py, DataRepo/views/models/bst/base.py, DataRepo/views/models/bst/client_interface.py, DataRepo/views/models/bst/column/many_related_group.py, DataRepo/views/models/bst/list_view.py, DataRepo/views/models/bst/utils.py, DataRepo/views/utils.py, DataRepo/widgets/bst/rows_per_page_select.py
Added the ability to automatically create column groups if there are multiple columns from the same many-related model.
Details:
- Removed BSTBaseListView's searchcols instance attribute.  That was a leftover from the way the prototype worked and it was only being used in an error, so I generated it on the fly from the columns and removed it from the constructor.
- Added a __str__ method to BSTColumnGroup.
- Added method add_check_groups to BSTBaseListView to automatically create column groups or issue warnings if a manually added group is missing a column.
- Added a private method '_get_group_representative' called from add_check_groups that selects the best representative field from a many-related model.
- Added a subset argument to select_representative_field to be able to restrict the …
=> `BSTListView` 14: Automatically added `BSTColumnGroup`s

DataRepo/templates/models/bst/paginator.html, DataRepo/tests/templates/widgets/bst/test_rowsperpage_select_option.py, DataRepo/tests/views/models/bst/test_utils.py, DataRepo/tests/widgets/bst/test_rows_per_page_select.py, DataRepo/views/models/bst/utils.py, DataRepo/widgets/bst/rows_per_page_select.py
This involved only 1 javascript change embedded in the `paginator.html` template.  The crux of the fix was in the `BSTRowsPerPageSelect`'s `get_context` method.
Fixed the javascript listener attachments to the rows per page select list by fixing the element name assignment from the context.
Details:
- Improved the ability to supply a custom option name to BSTRowsPerPageSelect
- Modified BSTRowsPerPageSelect.get_context to set the option_name in the context for each option.
- Added an option_elem_name keyword argument to the SizedPaginator constructor.
- Fixed the position of the option name argument in the initPaginator call in paginator.html
- Partially addresses #1585
- Specifically, this fixes this issue identified in [this comment](https://github.com/Princeton-LSI-ResearchComputing/tra …
=> `BSTListView` 15.4: Fixed the javascript listeners added to the rows per page select list
