- .flake8
- .github/workflows/superlinter.yml
- .isort.cfg
- .markdown-lint.yml
- .pylintrc
- .python-lint
- CONTRIBUTING.md
- DataRepo/admin.py
- DataRepo/apps.py
- DataRepo/models.py
- DataRepo/tests.py
- DataRepo/urls.py
- DataRepo/views.py
- README.md
- TraceBase/asgi.py
- TraceBase/settings.py
- TraceBase/urls.py
- TraceBase/wsgi.py
- manage.py
- requirements.txt
- requirements/common.txt
- requirements/dev.txt
- requirements/prod.txt
This Pull Request sets up a GitHub Actions workflow that runs the GitHub Super-Linter on the entire codebase. It also formats the files according to the standards specified by the linters.
Super-Linter is a collection of `bash` scripts that run various "standard" linters for many different types of files. The hope is that this helps to:
* Prevent broken code from being uploaded to the default branch (main)
* Help establish coding best practices across multiple languages
* Build guidelines for code layout and format
* Automate the process to help streamline code reviews
The linters that are in use right now are:
* [Markdown-lint](https://github.com/igorshubovych/markdownlint-cli#readme) - `.markdown-lint.yml`
* [Flake8](https://flake8.pycqa.org/en/latest/) - `.flake8`
* …
> Configure GitHub Actions to run Super-Linter

- .github/workflows/tracebase-tests.yml
- CONTRIBUTING.md
- DataRepo/tests.py
- TraceBase/settings.py
Postgres service is setup and Django tests are run using `pytest-django` in a GitHub Action workflow on every push.
A dummy test was created to ensure that tests run properly, but real tests should be created for any new functionality. 
The Django tests create a new database for testing, thus the `tracebase` Postgres user must be granted privileges to create a database in order to run tests. This step was added to `CONTRIBUTING.md`.
For running on GitHub Actions, a default `SECRET_KEY` is used.
> Setup GitHub Actions workflow to run Django tests

- .github/workflows/superlinter.yml
- .jscpd.json
- .mypy.ini
- .python-black
- CONTRIBUTING.md
- DataRepo/tests.py
- TraceBase/settings.py
- requirements/dev.txt
Having the `.github` regular expression seemed to exclude all files from linting, instead `\.github` is used.
Super Linter ignores files in the `.gitignore` by default now, so some exclusions were not needed (`.venv`, `__pycache__`)
Running linters on all python files (including migrations) does not cause any harm, and simplifies the configuration, thus `migrations` is no longer excluded.
There are two exceptions to this, the `jscpd` and `mypy` linters do complain about the migrations, thus they are configured to ignore those files.
None
There was considerable duplication in `tests.py` which caused jscpd to complain, thus the tests for sample related data was consolidated into a single setup method with multiple test functions instead of spread over various classes.
Since the files in the …
> Fix Super Linter excludes

- requirements/common.txt
Upgrade to patched version of Django 3.1.8
Address [CVE-2021-28658](https://github.com/advisories/GHSA-xgxc-v2qg-chmh)
Developers should update their virtual environment:
pip install -r requirements/dev.txt
None
None
> Upgrade Django to 3.1.8

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- .github/workflows/superlinter.yml
- CONTRIBUTING.md
Comments were added to to have `markdownlint` skip the MD041
first-line-heading errors on the github issues and pr templates. This
allows us to have the rest of the templates linted and explicitly
indicates the exception we decided to make. It also simplifies to the
superlinter config.
None
None
> Restore linting to .github directory

- DataRepo/models.py
- DataRepo/tests.py
Ensure that the value_from_choices_label function returns the value
corresponding to the label passed as a parameter
Add test to check the data loaded is correct
- Resolves #89 
The variable name `label` was overwritten while looping through the choices.
> Fix value_from_choices_label

- .flake8
- .github/workflows/superlinter.yml
Auto-generated migrations files do benefit from linting
- Resolves #56 
Also exclude `.venv` and `migrations` in `.flake8` config to make it
simpler to run flake8 on the entire repo from the commandline
> Exclude migrations from Super Linter checks

- DataRepo/models.py
- DataRepo/tests.py
Add computed values to `PeakData` and `PeakGroup` using the [`@cached_property`](https://docs.djangoproject.com/en/3.2/ref/utils/#django.utils.functional.cached_property) decorator on instance methods.
- Resolves #41 
- Resolves #42
The tests I added were based on the [computations peformed by @mneinast](https://docs.google.com/spreadsheets/d/1v2xi-mTwkGCezjNiv9Tc-0aql9jhra7u1SnmuqFY980/edit?usp=sharing). The first worksheet in the spreadsheet has [AccuCor corrected values that do not match](https://tracebase.slack.com/archives/C01M97YLQE5/p1622060075004700?thread_ts=1622054657.003900&cid=C01M97YLQE5) the ones I found for the `BAT-xz971` sample for `glucose`. I made a copy of the sheet and replaced the corrected values with the ones I saw in the example data and used the resulting values …
> Peakgroup computed values

- DataRepo/templates/peakgroups_results.html
- DataRepo/views.py
Added a prefetch_related after the filter of the search term.
none
The run time of the search is less than halved.  Initial testing was done without serum data and resulted in a load of around 12 seconds.  With serum data, it takes anywhere from 27 to 55 seconds (not sure what the factor is which determines the variability).
Searching all other models is reasonably fast.
The remaining bottleneck seems to be the cached_property fields.
> Performance improvement of basic search

- DataRepo/tests/test_models.py
Add tests for the `Procotol.Retrieve_protocol` method.
> Add tests for Protocol.Retrieve_protocol

- .github/workflows/superlinter.yml
- DataRepo/management/commands/load_samples.py
- DataRepo/utils.py
- requirements/dev.txt
* Update to superlinter v4
* Update linters in requirements/dev.txt to versions used by superlinter v4
* Set mypy type ignore on imports
Some imports are not PEP 561 compliant and thus mypy does not have the
proper type hints. One option is to install PEP 561 compliant stub
packages, however, it is not practical to install packages when
running superlinter, thus we'll just have mypy ignore these for now.
See
https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-type-hints-for-third-party-library
for more information.
None
None
> Update to superlinter v4

- DataRepo/compositeviews.py
- DataRepo/forms.py
- DataRepo/tests/test_views.py
- DataRepo/views.py
There was some metadata for the composite views still in views.py.  This effort extracted that and consolidated those things in the advanced search composite view.  I also created a composite form view to have it be able to create the form_classes dict using the keys derived from the metadata class.
- Resolves N/A - it's an addendum to the last advanced search consolidation PR.
The goal here was to make it so no code changes are required in views.py to add a new search output format.
Basically, the output format keys "pgtemplate" and "pdtemplate" are no longer in views.py.  The root model class for each output format is now saved in each advanced search derived class in compositeviews.py.
I did not address metadata inside the javascript code.  I might do that eventually.  So currently, to …
> More consolidation of the composite view metadata.

- DataRepo/forms.py
- static/js/hierarchical_formsets.js
- Added a placeholder attribute to the text input field of the advanced search.
- Reduced the number of calls to getElementById
- Resolves #135
The real fix/workaround was the addition of the placeholder input attribute, which prevents Safari Autofill from causing a delay after clicking in the field and also results in suggesting phone numbers to enter into the field from their contact card on macOS.  Note, other browsers I tested did not have these issues.  Many suggested solutions on google/stack were tried and this was the only one that worked.
I also reduced the number of calls to getElementById in the javascript, thinking initially that it was that that caused the lag.  It did not end up being the cause of the lag, but is more efficient none-the-less, so I kept it.
- There's no way …
> Form field text entry delay fix

- DataRepo/compositeviews.py
- DataRepo/tests/test_views.py
The tracer compound foreign key in the animal table was superfluous.  Also removed a debug print.
- Resolves no issue - turned up when I looked through my last PR
Very simple.  Couldn't get superlinter to run though.  I'd moved the repo in my FS, which apparently broke something.
> Removed extra entry in one of the formats

- DataRepo/templates/DataRepo/animal_detail.html
- DataRepo/templates/DataRepo/compound_detail.html
- DataRepo/templates/DataRepo/msrun_detail.html
- DataRepo/templates/DataRepo/msrun_list.html
- DataRepo/templates/DataRepo/peakdata_list.html
- DataRepo/templates/DataRepo/peakgroup_detail.html
- DataRepo/templates/DataRepo/peakgroup_list.html
- DataRepo/templates/DataRepo/peakgroupset_detail.html
- DataRepo/templates/DataRepo/protocol_detail.html
- DataRepo/templates/DataRepo/sample_detail.html
- DataRepo/templates/DataRepo/study_detail.html
I also took the liberty to:
- Added record names to detail page titles and headers
- streamline some field names
- obfuscate MSRun record IDs from the user (since they are autofields and can change).
- Resolves #152
For the MS Run "name", I used researcher and date, which is most likely unique, though not technically unique.  I didn't figure it would be critical to also show the protocol and sample, but invite feedback on changing that.
I arbitrarily changed "details" to "record".  Feel free to ask me to change that back.  I just thought it flowed better with adding the name to the header/title.
I also took the liberty to streamline some of the field names in the column headers and detail field headers, just to avoid a bit of redundancy.  I'll restore them if that's the consensus.
> Added record names to detail page titles and headers

- DataRepo/models.py
- DataRepo/tests/test_models.py
Added Sample.peak_data_queryset, with optional compound filter
Added Animal methods for serum sample(s) retrieval, and serum tracer peakdata
Added some rudimentary tests for the above
These are methods I thought might be useful for a first-step on the road to fcirc (and related) serum data calculations.  They could probably be expanded on.
This does not resolve any issues, _per se,_ but add some methods that might be usefully employed in #43 (groundwork)
If the naming or labeling of the methods can be improved, or you think they are not particularly useful, speak up (just a draft idea).  I just though they might be useful , prior to a subsequent calculation-based PR.
> Draft methods to retrieve tracer samples/peakdata

- DataRepo/tests/test_views.py
Test getAllComparisonChoices
This test is reliant on the value of `BaseSearchView.ncmp_choices`, which is good and bad. We could extract the logic to a static utility method and make testing more encapsulated that way, but I decided that was perhaps overkill.
> Test getAllComparisonChoices

- .python-lint
- DataRepo/models.py
- DataRepo/tests/test_models.py
- requirements/dev.txt
Added 2 new convenience methods: intact_tracer_peak_data, final_serum_sample_tracer_peak_group
Added 13 new methods for serum tracer calculations
Added preliminary tests for serum tracer calculations.
Briefly describe the changes in this pull request (not intended as a full
recounting of the issue description).
**Animal instance methods added:**
intact_tracer_peak_data
final_serum_sample_tracer_peak_group
tracer_Rd_intact_g
tracer_Ra_intact_g
tracer_Rd_intact
tracer_Ra_intact
tracer_Rd_avg_g
tracer_Ra_avg_g
tracer_Rd_avg
tracer_Ra_avg
tracer_Fcirc_intact
tracer_Fcirc_avg
tracer_Fcirc_intact_per_mouse
tracer_Fcirc_avg_per_mouse
tracer_Fcirc_avg_atom
**Tests added:**
test_tracer_Rd_intact_g
test_tracer_Ra_intact_g
test_tracer_Rd_intact
test_tracer_Ra_intact
test_tracer_Rd_avg_g …
> Added Animal methods/tests for serum tracer calculations

- DataRepo/tests/test_models.py
- DataRepo/utils.py
Fix some logic that was overwriting a dictionary of compounds so that Peakgroups that are named with two compounds separated by a slash ("/") are properly associated with two compounds
- Resolves #208
Note, this PR does **not** perform a data migration for the affected compounds, thus a database reload is necessary. A data migration can be added if we deem it necessary, but at this time, I thought the reload would be simpler, however, that does require work for all developers.
> Associate PeakGroups with mutiple compounds

- requirements/dev.txt
To ensure ipython works with python 3.6, we need to pin the jedi package
at an old version
https://github.com/ipython/ipython/issues/12677#issuecomment-826312842
None
This only affects development dependencies and is relevant for running ipython (`python manage.py shell`) under python 3.6.
> Pin jedi package version for compat with py3.6

- DataRepo/templates/DataRepo/search/results/peakdata.html
- DataRepo/templates/DataRepo/search/results/peakgroups.html
- static/css/hierarchical_formsets.css
As per today's meeting, this changes the table colors of the advanced search to match other tables.
- Resolves no recorded issue
I had to shift-reload to see the new colors.
> Adv Search color changes.

- DataRepo/utils.py
The tracer_compound_id column can sometimes be converted to a float,
then to a string, and then passed as lookup.
Possibly related to #255 (at least this issue stems from the conversion
of objects to values in the dataframe).
This is not a comprehensive fix, but did address the issues I was running into. Ideally, there would be some tests to reproduce this issue, but this is just a quick fix for now.
> Ensure id is not converted to float

- DataRepo/templates/DataRepo/search/results/fcirc.html
Fixes the hide/show functionality for "previous" rows in the fcirc advanced search results.
- Resolves #266
Trivial fix.  I did not lint or rerun tests because I think it's safe to assume that the main branch already passes everything and that these 2 character additions should not break anything.
> Added dot to bg-normal to identify it as a css class.

- .github/workflows/tracebase-tests.yml
Our current deploy server uses ~~3.6~~ 3.8, so test with that version.
Also, ensure the wheel package is installed for faster installation of requirements.
I have a request in to update the Python version on `tracebase-dev` ([RT #47075](https://gen-help.princeton.edu/Ticket/Display.html?id=47075)). When that happens, we should update the version that GitHub tests with.
> Specify Python 3.8 for GitHub Actions Testing

- DataRepo/templates/DataRepo/search/results/fcirc.html
Now show/hide updates of columns are executed on all changes to the table.
- Resolves #280
I'd tried `onSort`, but it had no effect.  Inspired by [this issue](https://github.com/wenzhixin/bootstrap-table/issues/1912), I used `onAll` instead, which is a bit overkill probably, but the safest option.
> Fixed show/hide updates upon various events in the fcirc template

- .jscpd.json
- DataRepo/templates/home.html
- DataRepo/tests/test_views.py
- DataRepo/views.py
- made big changes to the view for home page. Handled card attributes in views, instead of repeated code blocks in template.
- passed the linting with jscpd
- Resolves #279 
Added test code to spot check object counts, and urls for card attributes.
> changes to views and template for home page

- CONTRIBUTING.md
- DataRepo/management/commands/load_study.py
load_study wasn't overriding the parent because the key was wrong.  I corrected the key [based on the yaml schema](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/9db1217c6b61a1de55cee2057e9c7cfd85ac88f3/DataRepo/schemas/load_study.yaml#L33).
I also updated the load compounds command in CONTRIB.
Encountered when trying to create a yaml to load the KR infusion data.  Kept getting the error:
```
Mass spectrometry run with this Researcher, Date, Protocol and Sample already exists.
```
The only msrun_protocol that was loading was the unused parent one:
```
Found msrun_protocol protocol 2 'Default'
```
Once I made the change, I stopped getting the error and the studies loaded with the protocols I was setting per file, e.g.:
```
Finding or inserting …
```
> Setting msrun_protocol per file in the loading.yaml file was broken

- DataRepo/templates/DataRepo/search/results/fcirc.html
Edited initial show/hide state of animal metadata columns in the fcirc template
- Resolves #270 (when combined with previous PR)
Note I noticed & reposted a [bootstrap-table bug](https://github.com/wenzhixin/bootstrap-table/issues/5991) when testing this.  `Toggle all` leaves the first column checkbox (Animal) checked and grayed out even though the column is hidden.
This PR is configured to merge into the previous PR's branch so that you don't re-review the same code.
For some reason, I thought this was going to be more involved than it turned out to be, which is why I separated the effort.
> Edited initial show/hide state of animal metadata columns in the fcirc template

- DEVELOPMENT.md
Header lines are no longer commented in `tsv` files (#267), thus update
the docs to reflect that change.
- Resolves #267
> Update docs regarding commented header line in tsv

- DEVELOPMENT.md
- DataRepo/compositeviews.py
- DataRepo/templates/DataRepo/search/results/peakgroups.html
- DataRepo/tests/test_views.py
- DataRepo/views.py
Changes the models datamember in each BaseSearchView class to model_instances, treating the old model keys as model instance names and added the actual model to the inner dict.
I changed the Compound model (instance) in the peakgroups format to TracerCompound and then added MeasuredCompound as a proof that it works.
- Resolves ##296
The models in the new model_instances datamember are not actually used.  They are mainly just labels.  The only thing they're used for in the conversion of a basic search to an advanced search.
I added a backup method of obtaining the right model instance.  If a link is created for example, to "Compound", the initial lookup won't find it, but it will fall back to the model contained in each instance.  If there's only one, it returns the model instance name. …
> Now a model can be in a composite view more than once.

- DataRepo/fixtures/tissues.yaml
- DataRepo/tests/test_views.py
Add the lymph node tissue type, required by the fluxomics 2020 dataset (#250).
> Add lymph node tissue type

- DataRepo/management/commands/load_study.py
- DataRepo/schemas/load_study.yaml
Allow load_study config to specify the `skip-researcher-check` option on
load_animals_and_samples. This simplifies loading of files that contain
multiple researchers.
This issue came up during my attempts to load the fluxomics 2020 study data (#250).
> Add skip-researcher-check option to load_study

- DataRepo/templates/DataRepo/animal_detail.html
- DataRepo/templates/DataRepo/animal_list.html
- DataRepo/templates/DataRepo/compound_detail.html
- DataRepo/templates/DataRepo/compound_list.html
- DataRepo/templates/DataRepo/sample_list.html
- DataRepo/templates/DataRepo/search/results/fcirc.html
- DataRepo/templates/DataRepo/search/results/peakdata.html
- DataRepo/templates/DataRepo/search/results/peakgroups.html
- DataRepo/templates/DataRepo/study_detail.html
- DataRepo/templates/DataRepo/study_list.html
- DataRepo/templates/DataRepo/study_summary.html
- DataRepo/templates/base.html
Fixed the numeric sort for the case where bootstrap table's default sort messes up when a tooltip with a variable number of decimal places is present.
- Resolves #305
I set an arbitrary max number of decimal places for the tooltip values (10 for values greater than 1 and 15 for values less than 1).  My original intent of the tooltip was to show the *unmodified* value.  The thought was to be able to search for an exact value and also know what you would get in the download (which still does not modify the value).  These modifications back-fill zeroes when the places are below the threshold and truncate anything longer than the threshold.  I did not check the DB for how many decimal places are possible, but these arbitrary settings are likely overkill.
While working out what was going on, I …
> bootstrap table numeric sort fix

- DataRepo/templates/navbar.html
I edited the google form to create a field for the page that the clicked feedback link was on.  I expect this could potentially be useful to put any comments a user submits in the proper context.  Please consider making suggestions to edit that field prompt...
[Google form edit page](https://docs.google.com/forms/d/1DdC6BtOEZZYsrc06yh4Akt6sMkFmHuICrT6ew1qLUMM/edit)
[Google form submission page](https://docs.google.com/forms/d/e/1FAIpQLSdnYe_gvKdoELXexZ9508xO8o59F1WgXcWBNh-_oxYh9WfHPg/viewform?usp=pp_url&entry.1881422913=Tracebase+path+will+be+prefilled+here)
I also slightly reordered the admin & advanced search items.
- Resolves #308
I was annoyed that I couldn't hide the field containing the referred URL in the google form.  If you figure out a way to do that that's straightforward, …
> Added feedback link

- DataRepo/templates/DataRepo/search/results/peakdata.html
The header for the measured compound column was missing.
- Resolves #313
nothing of note.
> Added missing PeakData header

- .github/workflows/tracebase-tests.yml
The `HMDB_CPD_URL` is not hardcoded as part of the class.
> Remove HMDB_CPD_URL from test ENV

- .github/workflows/superlinter.yml
- CONTRIBUTING.md
The [Super Linter slim
image](https://github.com/github/super-linter#slim-image) brings the
image size down by 2gb and drastically speeds up the build and download
time.
The only linters removed from the slim version are:
* `rust` linters
* `dotenv` linters
* `armttk` linters
* `pwsh` linters
* `c#` linters
> Use Slim version of Super Linter

- DataRepo/management/commands/load_study_set.py
Add a command to read a file of file names and use those as
`study_params` for the `load_study` command.
- Resolves #327
This PR is missing tests, though I did test it using the data in https://github.com/PrincetonUniversity/tracebase-rabinowitz-data. I would include a test when we organize example and test data (#172 and #325).
> Add load_study_set command

- DataRepo/forms.py
- DataRepo/templates/DataRepo/search/query.html
- DataRepo/views.py
- static/js/hierarchical_formsets.js
Restored the form validation error about required fields.
- Resolves no issue, but related to #132
The refactor of nested_forms.js to hierarchical_formsets.js awhile back inadvertently removed the required field error last seen [here](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/ec691f3ede85496625225f8bad3d026594c8d714/static/js/nested_forms.js#L101).
This is a simpler quick fix.  I couldn't re-do it the other way because of the code that changes the search term field type, but there's only 1 type of form validation error (other than those that would result from hacking the form submission).
- Removed an outdated todo comment from form.py
- Removed a few console debug prints.
- Filled in a missing argument in a recursive call to `saveSearchQueryHierarchyHelper` (which …
> Fixed search validation error

- DataRepo/templates/DataRepo/compound_detail.html
Replaced exact with iexact
- Partially Resolves #339
Making this change on github because it's simple and my clone is in the middle of an edit.  The bug is in 2 other detail templates, so I will submit them individually.  I won't close #339 until I have implemented an error when an invalid ncmp value is supplied.
> Basic search links fixed in compound detail

- DataRepo/templates/DataRepo/study_detail.html
'exact' is not fully supported.  Changing it to the supported 'iexact'.
- Partially Resolves #339
Making this change on github because it's simple and my clone is in the middle of an edit.  The bug is in 2 other detail templates, so I will submit them individually.  I won't close #339 until I have implemented an error when an invalid ncmp value is supplied.
> Basic search links fixed in study detail

- DataRepo/compositeviews.py
- DataRepo/forms.py
- DataRepo/templates/DataRepo/search/query.html
- DataRepo/tests/test_compositeviews.py
- DataRepo/tests/test_views.py
- DataRepo/views.py
- static/js/hierarchical_formsets.js
See the resolved issue for details, but basically now when a user selects fields in any/all formats and executes a search, those selections will all be remembered if the user switches formats again after the search was executed.
- Resolves #229
I added these methods to the BaseAdvSearchView class:
- `getSearchFieldChoicesDict` - saves the fld select lists that should be set by javascript based on the selected output format.  This structure is passed from the view to the template, which is then consumed by javascript to make the dynamic updates.
- `getAllSearchFieldChoices` - saves the flattened fld select list as a single tuple. This is used by the form class to validate the fld select lists for every format.  However, it's checked by the selected format's class, so it needs to have all …
> fld selections are now remembered between searches

- DataRepo/hier_cached_model.py
- DataRepo/models.py
- DataRepo/tests/test_hier_cached_model.py
- DataRepo/tests/test_models.py
- DataRepo/utils.py
Added tests to the caching code and fixes a few bugs (that didn't affect regular caching operations).
- Fixed a test in test_models.py
- Removed the cache building methods from HierCachedModel because I couldn't figure out how to do it without importing the derived classes.
- Made get_my_cached_method_names a class method.
- Changed the use_cache variable to caching_retrievals because it was too confusing in the testing.
- Created a delete_all_caches method so that files using this file don't also need to import django.core.cache
- Changed get_result to not consult the root record via caches_exist, because I realized that you cannot infer cache invalidity from the representative - only validity.  Any invalidation is/must be handled via immediate deletion of all affected cached values.
- …
> Caching tests

- DataRepo/utils.py
Minor change to sort the output in the error message when sample lists don't between original and corrected sheets in an AccuCor file.
- Addresses @hepcat72 's comment: https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/359#discussion_r799613570
> Sort lists in sample check error message

- DataRepo/forms.py
- DataRepo/multiforms.py
- DataRepo/pager.py
- DataRepo/templates/DataRepo/search/results/display.html
- DataRepo/templates/DataRepo/search/results/fcirc.html
- DataRepo/templates/DataRepo/search/results/peakdata.html
- DataRepo/templates/DataRepo/search/results/peakgroups.html
- DataRepo/templates/pagination.html
- DataRepo/templatetags/customtags.py
- DataRepo/views.py
I have re-introduced the ability to sort the advanced search results, only now using server-side mechanisms.  I also fixed an issue with the "toggle all" column switch control to be able to remembered from page to page.  With that, I realized that there needed to be a way to reset the column switch selections back to default, so I added a "Reset" button to the controls over the table at the top right.
Unfortunately, with server-side sort, it's no longer possible to sort the calculated field columns, because the `.order_by()` method doesn't support it.
Also fixed the peakdata column header issue.
And I reduced code redundancy by having `getAllBrowseData` call `performQuery`.
- Resolves #336
- Resolves #365
I addressed issues from the previous PR, so you can assess those changes and …
> Server-side Advanced Search Results Sorting

- DataRepo/templates/DataRepo/search/query.html
- DataRepo/templates/DataRepo/search/results/display.html
- DataRepo/templates/DataRepo/search/results/fcirc.html
- DataRepo/templates/DataRepo/search/results/peakdata.html
- DataRepo/templates/DataRepo/search/results/peakgroups.html
- DataRepo/urls.py
- DataRepo/views.py
This makes it possible to render any of the advanced search output formats by supplying it a queryset and 2 other basic parameters:
- `mode` (with the value `view`)
- `format` with 1 of 3 possible values:
- `pgtemplate` (for peakgroups)
- `pdtemplate` for peakdata
- `fctemplate` for fcirc
- Resolves #371
I included a temporary function in views.py called `test_barebones_advanced_search` to demonstrate how you can call the template.
I basically just added checks on the new mode to decide whether to render things in the template that depend on various context variables being present.
I consider this implementation a first (very simple) step.  I think the next step would be the ability to show an empty search interface above the results (the same way there is one when in "browse" mode).
> Made the Advanced Search templates work with a barebones context

- DEVELOPMENT.md
- DataRepo/compositeviews.py
- DataRepo/templates/DataRepo/search/results/fcirc.html
- DataRepo/templates/DataRepo/search/results/peakdata.html
- DataRepo/templates/DataRepo/search/results/peakgroups.html
- DataRepo/templatetags/customtags.py
- DataRepo/tests/test_compositeviews.py
- DataRepo/tests/test_customtags.py
- DataRepo/views.py
If/when we decide to split the presentation of any records in separate HTML table rows (e.g. show 1 peak group in multiple rows (one for each of multiple labeled elements)), this PR makes that do-able.  It fixes the record count to reflect the number of rows in a "joined" table, as if doing a real SQL left join.
- Resolves #367
This code is actually a work-around.  Django always returns records of the "root" table that was queried only - not a set of joined records.  So in order to get an accurate count of a "joined" table, as would be presented in the template, it needs to return duplicates of the root table, which Django does do based on the relationships, just without the M:M record associations.  Those duplicates exist, but the code was written previously to eliminate them with a call …
> Split row counts now accurate

- DataRepo/migrations/0001_initial.py
- DataRepo/models/animal.py
- DataRepo/models/compound.py
- DataRepo/models/msrun.py
- DataRepo/models/peakgroup.py
- DataRepo/models/researcher.py
- DataRepo/models/sample.py
- DataRepo/models/utilities.py
- DataRepo/tests/test_models.py
- DataRepo/utils.py
Since `TracerLabeledClass` is used as model baseclass, we had to update
it's location after moving it.
Also, this fixed imports to get the tests in `test_models.py` running.
```bash
python manage.py test --pattern="test_models.py"
```
> Update TracerLabeledClass base class in migrations

- DataRepo/compositeviews.py
- DataRepo/forms.py
- DataRepo/pager.py
- DataRepo/templates/DataRepo/search/results/display.html
- DataRepo/templates/DataRepo/search/results/stats.html
- DataRepo/templates/pagination.html
- DataRepo/templatetags/customtags.py
- DataRepo/tests/test_compositeviews.py
- DataRepo/tests/test_customtags.py
- DataRepo/tests/test_views.py
- DataRepo/views.py
Added stats for advanced search results as requested [here](https://docs.google.com/document/d/1HCdqFgIDjGeaA8p1M8ElZhWuwxuczVvfwdydhuhLPUo/edit).
- Resolves #159
Here's roughly how it works:
When a search is first performed, the stats are not generated because since it has to look at *all records*, it can take awhile.  Worst case, when I tested with **all peak data** using everything through the fluxomics study, it took 51 seconds.  So in order to not slow down the search, I incorporated the stats compilation with the paging form.  If the user clicks the new stats button, they immediately get a message that it might take a minute.  It calculates all the stats and passes those results from page to page - so it only needs to compile the stats once per search.  If they never click the stats …
> Search stats

- DataRepo/compositeviews.py
- DataRepo/templates/DataRepo/search/results/display.html
- DataRepo/tests/test_views.py
- DataRepo/views.py
The stats button should not appear on the FCirc results page because no stats are defined for that format.  It now does not display when stats are not defined.
I believe this worked in an earlier version of the search stats implementation, but when I added the ability to remember stats during paging, it got broken and I didn't notice.
There are no stats configured for the FCirc format - the only stats Michael requested were for cached property fields, which could not be done in the current implementation.  So the stats button should not even appeat to be clicked on the FCirc results page.
It was checking the stats context variable, which originally was None I think, for Fcirc.  But in adding the transit of stats between pages, I wrapped it in a larger …
> Fixed a minor bug regarding the revealing of the stats button

- DataRepo/forms.py
- DataRepo/multiforms.py
- DataRepo/pager.py
- DataRepo/templates/pagination.html
- DataRepo/views.py
`multiforms.py` was refactored so that the advanced search class in views.py no longer needs to override the post method.
I misunderstood both the intent of multiforms and how it was implemented, thus when I applied it, my efforts did not jive with the original code.  Now it does.  Here are some of my key misconceptions about multiforms, what I originally did, and how I changed it to conform to the original design:
- Multiforms was written so that a single view can handle multiple types of form submissions (in no way does it do anything special to handle formsets (multiple instances of the same form type (i.e. copies of the same form inside one pair of form tags)).  This involves a few key mechanisms:
- Identify the form that was submitted
- Bind the correct form class to the submitted …
> Multiforms refactor

- DataRepo/formats/dataformat.py
- DataRepo/formats/dataformat_group.py
- DataRepo/tests/test_formats.py
Django's resolving of model field references to database fields uses different strategies in the `.distinct()` method than it does in the `.order_by()` method.  If there's a foreign key in the `meta.ordering` that is supplied to order_by(), it resolves to the referenced model's `meta.ordering`.  But the same field supplied to distinct resolves to the ID field saved in the referring table.
This fix recursively resolves the fields in both cases, because django requires the ordering fields and distinct fields to match.  Otherwise, there's a programming error.
- Resolves #424
Comments in-line to explain things.
> Fixes the SQL construction bug

- DataRepo/tests/test_infusate_name_parser.py
- DataRepo/utils/infusate_name_parser.py
* Added parsing of isotope data into constituent parts
* Use custom exceptions
* Added some tests for isotope and tracer level parsing
@jcmatese, I took the liberty of adding some additional parsing to this PR. I mostly built off of what you already had. I believe there may be some edge cases that aren't well handled right now, so I'd appreciate some additional tests being written for this. Just having the example string and desired output dictionary (or exception) would be helpful to make it simpler to add in any additional checks are modifications to regular expressions.
> Parse isotope data

- DataRepo/tests/test_infusate_name_parser.py
- DataRepo/utils/infusate_name_parser.py
Simplified the regular expressions.  Added the usage of `TracerLabeledClass` to get the element names (which will have to be changed to `ElementLabel` after merge in order to pass tests/linting).
- Resolves review issues in PR #441
There are a few things to note...
- I'll be on vacation during review, so if there are any blocking issues, feel free to fix them or merge #441 and I can address them and merge upon my return
- I changed the string used in test `test_malformed_infusate_parsing` because the original test wasn't testing the infusate pattern - it was testing the isotope pattern, which is tested elsewhere.
- I added a parameter called `parse_one` to `parse_tracer_string` because the regex used is not anchored (because it's used by `findall`.  So set `parse_one` to `True` if the …
> Suggestions for the infusate parsing PR

- DataRepo/tests/test_infusate_name_parser.py
- DataRepo/utils/infusate_name_parser.py
Just adding a utility file and some basic tests for **_parsing_** the initial infusate naming specification.
- touches part of #407 based on proposal in #364 
**_Important: It does NO validation_**, yet.
My assumption is that these functions will/might not remain in this new file(s), but might be moved elsewhere in the codebase including possibly the new models.
It would be helpful for reviewers to focus on 
- the regular expressions for infusate and tracers, if they can be usefully improved
- the data structures used to store the parsed bits, because presumably other code that consumes these pieces (validators, etc) will have to access them
- additional positive and negative tests, beyond the basics in the PR
- a proposed fix for this …
> Functions and tests for infusate name parsing

- DataRepo/tests/test_infusate_name_parser.py
- DataRepo/utils/infusate_name_parser.py
Given the edit while I was gone, I noted that the choice I'd made after removing the unparsed `labeled_element` and selecting to rename `element` to `labeled_element` for consistency was reverted to `element` to match the model.  I agree with the motivation behind that change and this PR extends that edit to apply to the other dictionary keys as well.
I also note that the removal of the `parse_one` argument was a good one.  It was made redundant when I added the requirement to make the tracer name not contain a match to the isotope encoding pattern.
Fixed a typo.
- already resolved issue / no issue
self-explanatory.
> Consistency edits and typo correction

- DataRepo/tests/models/test_peak_data.py
The `PeakDataLabelTests.setup()` method creates a PeakDataLabel, so the test for a conflict only needs to create a single PeakDataLabel record.
> Remove extra PeakDataLabel creation from test

- .github/workflows/tracebase-tests.yml
- DataRepo/management/commands/rebuild_maintained_fields.py
- DataRepo/models/animal.py
- DataRepo/models/maintained_model.py
- DataRepo/models/researcher.py
- DataRepo/models/sample.py
- DataRepo/templatetags/customtags.py
- DataRepo/tests/models/test_animal.py
- DataRepo/tests/models/test_infusate.py
- DataRepo/tests/models/test_sample.py
- DataRepo/tests/test_infusate_parsing_validation.py
- DataRepo/tests/test_queryset_to_dataframes.py
- DataRepo/tests/test_views.py
- DataRepo/tests/tracebase_test_case.py
- DataRepo/utils/sample_table_loader.py
Replaced the buffered update U erroneously removed 8 commits ago.
self explanatory.  I should probably add a test, but I gotta run.
- Tests
> Fixed an issue with sample table load auto-updates.

- DataRepo/templates/DataRepo/search/results/fcirc.html
- static/js/hierarchical_formsets.js
Added a way to detect in the search form if the search had already been manipulated and if so, use a different strategy to change the search based on the checkboxes that prevents the groups to keep propagating.
- Resolves review issue in PR #516
It looks like a lot of code, but it's variations on a theme.  Definitely could be streamlined or made simpler.  If you have any suggestions in that regard, please make them.
The basic concept is:
1. Is the first search row for the `is_last` field?
2. If not, use the original strategy
3. If so, and the group has 2 members, the second being a group: Remove the is_last search criteria and prepend the new is_last search criteria
- Tests
> Prevent the search structure from getting deeper and deeper when last/prev checkboxes manipulated

- static/js/hierarchical_formsets.js
When I implemented the FCirc re-pagination issue, I realized that the code could be better encapsulated and streamlined to make it easier to follow, understand, and modify.
This refactor makes some very slight interface modifications, but effectively is no different to users.  The one thing that is different is that the previous/last checkboxes on the FCirc results page now result in a full form row to be rendered before form submission.  Before, it was only adding the `fld` and `ncmp` select lists, along with the various `val` widgets and other hidden fields.  It wasn't adding the buttons: `-`, `+`, and `++`.  Now that that's all encapsulated in a single function that creates the row, those buttons are added.
The creation of groups isn't as encapsulated as I'd like because the `+` and …
> Javascript refactor

- DataRepo/models/animal_label.py
- DataRepo/models/peak_group_label.py
Caught an exception due to multiplying None by an int in 2 places.  It was causing an exception during download and an exception if the affected record was ever attempted to be displayed.
- Resolves #539
When I reworked this code, I had revamped the exception catches.  Looks like I pruned them back too far.
- Tests
> Fixed an exception caused by division by 0.

- DataRepo/models/tracer.py
- DataRepo/tests/models/test_infusate.py
- DataRepo/tests/models/test_tracer.py
- DataRepo/tests/test_infusate_parsing_validation.py
- DataRepo/tests/test_queryset_to_dataframes.py
I changed the tracer model code to wrap the list of isotopes with `[]` instead of `()` and updated the tests to expect square brackets.
- Resolves #542
~~**Important note**: This leaves the dataframe tests broken.  I had started to look into it and realized there would be a learning curve given my unfamiliarity with how the dataframe code works, as I did not understand what was causing the tests to fail, so I decided to request @fkang-pu's help in fixing them.  For all I know, it could be possible that the source of the problem is my code (or the example data?), but the only indication in the tests to get at the source is through the failing dataframe tests.  So Fan would be better suited to efficiently finding the problem, so I suggest branching off the branch in this PR and submit a PR …
> Changed the wrapping isotope characters from parenthases to square brackets

- DataRepo/models/animal_label.py
- DataRepo/models/peak_group.py
- DataRepo/models/tracer.py
- DataRepo/models/utilities.py
- DataRepo/utils/accucor_data_loader.py
Replaced calls to Compound.atom_count() when the formular was available in an associated peakgroup, to calls to atom_count_in_formula in models.utilities.
- Resolves #474
I was able to remove loops that involved the 1:M PeakGroup:Compound relationship.
- Tests
> Made atom counting more efficient

- DataRepo/templates/base.html
- static/css/extras.css
Added a class in extras.css called `main-content` that sets the width as 100% - 9rem.  9rem is the width of the sidebar.
- Resolves #572
If you know how to use a css variable to have the sidebar width of 9rem in 1 place instead of 2, please suggest the change.  Even better, if bootstrap has a builtin way of managing responsive width, then please call attention to it.  I suspect it does, but I don't know how to take advantage of it.  I think that setting a static width for the sidebar is the original edit that created this issue and that the previous content width of 90% just didn't play well with that static width, which caused elements on the right side in floating divs caused them to be pushed further and further off the right side as the window width was reduced.
The result of this …
> Added a calculation for the width of the main "panel"

- DataRepo/templatetags/customtags.py
- DataRepo/tests/test_queryset_to_dataframes.py
- DataRepo/tests/test_views.py
- DataRepo/utils/queryset_to_pandas_dataframe.py
It took a lot of digging, but I found the source of the exceptions that were caused by null tracer names.  And I think it was isolated to tracer names and not infusate names.
- Resolves #513
I didn't craft the NullTolerance tests to do anything other that test that an exception isn't raised (other than an expected IndexError, because no results are expected when you search with a name and it's not there).
To do this, I added parameters/arguments to the appropriate superclass tests and call those tests from the derived test classes with modified dicts to account for the None values.
In the dataframe code itself, I added a couple try/catch blocks around some joins that were complaining about the null values.  I added tracer IDs to the dataframes so that the construction of the dataframes …
> Fix for dataframe null tracer name values causing 500 internal server errors

- DataRepo/models/peak_group_label.py
- DataRepo/templates/DataRepo/search/results/peakdata.html
- DataRepo/tests/test_formats.py
Fixed overlooked updates of `labeled_element` and `labeled_count` to `labels__element` and `labels__count`.
- Resolves an issue [Michael mentioned on slack](https://tracebase.slack.com/archives/C01M97YLQE5/p1668110922610469).
This was just an overlooked field path in a template.  I didn't check for others.  Easy-peasy.  I will merge upon first approved review.
- Tests
> Fixed overlooked updates of labeled_element and labeled_count

- .github/pull_request_template.md
- .github/workflows/tracebase-tests.yml
- DataRepo/tests/loading/test_loading_compounds.py
- DataRepo/tests/loading/test_loading_protocols.py
- DataRepo/tests/loading/test_loading_tissues.py
- DataRepo/tests/models/test_animal.py
- DataRepo/tests/models/test_compounds.py
- DataRepo/tests/models/test_fcirc.py
- DataRepo/tests/models/test_hier_cached_model.py
- DataRepo/tests/models/test_infusate.py
- DataRepo/tests/models/test_infusate_tracer.py
- DataRepo/tests/models/test_model_utilities.py
- DataRepo/tests/models/test_peak_data.py
- DataRepo/tests/models/test_sample.py
- DataRepo/tests/models/test_tracer.py
- DataRepo/tests/models/test_tracer_label.py
- DataRepo/tests/test_customtags.py
- DataRepo/tests/test_formats.py
- DataRepo/tests/test_infusate_parsing_validation.py
- DataRepo/tests/test_models.py
- DataRepo/tests/test_queryset_to_dataframes.py
- DataRepo/tests/test_views.py
- DataRepo/tests/views/test_home_views.py
- DataRepo/tests/views/test_protocol_views.py
Removed the multi_* test tags.
- Resolves #549
There were minor changes in the `protocol_user_validation` branch that made a few tests pass (a technicality of the inheritance).  Upon request, I can try and transfer that change into this branch to make it not branched off `protocol_user_validation`, but IMO, this branch is not mission critical - there's no effective change - so it can wait until the other branches merge.
- Tests
> Test tag cleanup

- DataRepo/templatetags/customtags.py
- DataRepo/tests/test_queryset_to_dataframes.py
- DataRepo/utils/queryset_to_pandas_dataframe.py
- Made changes to several methods in "queryset_to_pandas_dataframe.py" for handling null values in the following cases
- Animal.treatment_id
- Infusate.name
- Tracer.name
- TracerLabel.name
- Modified test code for DataFrames
- Simplified code for calling example datasets
- Consolidated tests into one class, and reconstructed cases for null tolerance tests.
- Resolves #585 
- The main change made to DataFrame code is to replace "null" values with a string assigned to `null_rpl_str`.  I opt to use "None" as it is consistent with web display of null values stored in database.
- Modified code for `obj_hyperlink` filter in `customtags` to control wrapping of values in lists (e.g. webpages for study, animal, and infusate). The webpages are more user-friendly with such change while the …
> Refactor DataFrame code for handling null values associated with treatment and infusate

- DataRepo/management/commands/load_accucor_msruns.py
- DataRepo/management/commands/rebuild_maintained_fields.py
- DataRepo/models/__init__.py
- DataRepo/models/maintained_model.py
- DataRepo/tests/loading/test_loading_protocols.py
- DataRepo/tests/test_models.py
- DataRepo/tests/tracebase_test_case.py
- DataRepo/utils/accucor_data_loader.py
- DataRepo/utils/protocols_loader.py
- DataRepo/utils/sample_table_loader.py
Added atomic transaction to the sample table loader and implemented associated tests.
- Phase 1
- `sample_table_loader` **(This PR is based on the other refactor PR that addressed these items in the sample_table_loader)**
- `accucor_data_loader`
- Phase 2
----
- Phase 3 **=== YOU ARE HERE ===**
----
- Phase 4
- `7.` Validation page works by running in dry-run mode on the main database
- Phase 5
- `8.` Remove the validation database
- `8.1.` Remove `.using(db)`, `.save(using=db)`, and `if self.db == settings.TRACEBASE_DB: rec.full_clean()`
- `8.2.` Revert database settings
- `8.3.` Update docs
- Partially addresses #580 - Implements phase 3
Small number of changes.  I kind of expected this PR to be more involved, because I expected there would be tests to fix.
I wrote a somewhat holistic …
> Refactor (phase 3) to remove the validation database - atomic transactions

- DataRepo/templates/upload.html
Fix the link to the sample table template on the upload page
- Resolves #639
- Tests
> Fix URL for sample table template on upload page

- DataRepo/forms.py
- requirements/common.txt
Django <= 3.2.18 allowed multiple files to be uploaded using a `ClearableFileInput`. However, this presented a security risk since only the first file was validated. This PR extends the `forms.FileField` to properly validate multiple submitted files.
Django <= 3.2.18 allowed multiple files to be uploaded using a `ClearableFileInput`. However, this presented a security risk since only the first file was validated. This PR extends the `forms.FileField` to properly validate multiple submitted files.
Source: https://docs.djangoproject.com/en/3.2/topics/http/file-uploads/#uploading-multiple-files
- Resolves #680
- Tests
> Update handling of multiple file uploads

- DataRepo/templates/DataRepo/search/results/peakgroups.html
- changelog.md
Templates now check enrichment fraction and enrichment abundance and display "None" if no value can be calculated.
- Resolves #611
Describe any areas of concern that code reviewers should pay particular
attention to.  E.g. There are significant logic changes in function X.
- Tests
> Display None when enrichment values are missing

- CONTRIBUTING.md
Include documentation about `ArchiveFile` in the `CONTRIBUTING.md` file.
- Resolves #719 
- Tests
> Include ArchiveFile information in CONTRIBUTING.md

- DataRepo/models/archive_file.py
- changelog.md
Having human readable default string representations for model classes makes the default admin interface much easier to read.
- Tests
> Use human readable str methods for ArchiveFile

- DataRepo/management/commands/load_animals_and_samples.py
- DataRepo/management/commands/load_compounds.py
- DataRepo/management/commands/load_protocols.py
- DataRepo/management/commands/load_study.py
- DataRepo/management/commands/load_tissues.py
- DataRepo/tests/loading/test_loading_compounds.py
- DataRepo/tests/loading/test_loading_protocols.py
- DataRepo/utils/compounds_loader.py
- DataRepo/utils/protocols_loader.py
- DataRepo/utils/sample_table_loader.py
- DataRepo/utils/tissues_loader.py
I updated issue #577 today, having to do with errors during load about novel protocols (and tissues and compounds).  Basically, I implemented the same strategy that was used to solve this same problem WRT accucor errors about missing samples - I deferred rollback of changes to be handled in `load_study`.
- Resolves #577
> Defer rollback for protocols, tissues, and compounds

- DataRepo/migrations/0016_protocols_to_lcmethods.py
This makes the migration MUCH faster.  I discovered the slowness because after my initial migration, I loaded new data on a different branch that was causing me errors, so I had to copy the method into the shell and run it manually.  It was taking forever and there were a lot of caching update messages, so I stopped it and added the caching update disable call and it finished in short order.
Straight-forward.
- Associated issue/pull request …
> Added a disable of caching updates to the LCMethod record migration

- .github/workflows/tracebase-tests.yml
- DataRepo/models/hier_cached_model.py
- DataRepo/models/maintained_model.py
- requirements/common.txt
This PR catches an handles exceptions thrown in Django 4.2 that previously were not thrown in 3.2.  There are potentially multiple possible fixes for this issue, but I believe this fix is the least complex and most effective fix, though it does have a caveat.
Here's the difference between 3.2 and 4.2 in a nutshell:
In Django 3.2, if you're creating an Animal object, it will have a null `samples` "related name" because `Sample` has a foreign key into `Animal`.  In Django 3.2, you could override `save` in a superclass and traverse this relation, e.g. `self.samples.count()` or `self.samples.filter(...)` and it would return either `0` or and empty queryset, respectively.
Django 4.2 disallows traversal of these un-set-up relations (probably due to some new functionality, who knows) and throws …
> Update to Django 4.2, with necessary changes due to changes in behavior of `save()`

- DataRepo/models/maintained_model.py
Added a check and set of the class's attributes if not set.
- Resolves an [issue](https://tracebase.slack.com/archives/C01LFSYQHN3/p1697049043747259) Lance encountered on main
This might not be the best or only way to fix this issue.  According to [this stack post](https://stackoverflow.com/a/20643172/2057516), it suggests I might be setting the `threading.local` values in an unsupported way, but I'm pretty sure I'd looked it up.
This PR fixes this error when you try to look at any model's `DetailView`:
```
Traceback (most recent call last):
File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/core/han …
```
> Fixed an issue with DetailViews relating to MaintainedModel's threading.local data

- DataRepo/models/maintained_model.py
- DataRepo/tests/loading/test_load_accucor_msruns.py
- DataRepo/tests/models/test_maintained_model.py
- DataRepo/tests/test_models.py
- DataRepo/tests/test_views.py
- DataRepo/tests/tracebase_thread_test.py
This is the planned follow-up to PR #766, to more formalize that quick fix.  The fix was easy, but I wanted to write some decent tests involving threads, which took the better part of a work-day equivalent.
There are 2 main changes:
1. The `MaintainedModel.data` class attribute for storing thread-local data (the `coordinator_stack` and `default_coordinator` for tracking the current coordinator context), is now comprehensively initialized in each thread, as-needed, and all access to that data was routed through getters that check and perform the initialization if needed.
2. The class attributes (and associated methods) of `MaintainedModelCoordinator` were moved to the `MaintainedModel` class, because since they don't have anything to do with coordinator context, and can be accessed via the …
> Comprehensive initialization of thread-local data in `MaintainedModel` for auto-update mode tracking

- DataRepo/formats/dataformat_group.py
- DataRepo/tests/test_formats.py
- DataRepo/tests/test_studies_exporter.py
- DataRepo/utils/studies_exporter.py
- DataRepo/views/search/basic.py
- Skips search field to display field conversion if `search_again` is `False` in the call to `createNewBasicQuery` (to avoid necessary code execution when not needed, i.e. when not rendering the search form, populated with the last performed search)
- Eliminates `Http404` exceptions from `DataRepo/formats/dataformat_group.py`
- Simplifies the database query inside `searchFieldToDisplayField`
- Eliminates any exception due to "no data"
- This does **not** simplify `searchFieldToDisplayField` to the point where it doesn't traverse the `qry` object.  That complex process is intended to support search queries that can match multiple different fields.  It has a flaw that is well documented: it does not support "or" groups in the `qry` structure.  We currently only use it for simple single …
> Eliminate export exceptions due to no data

- DataRepo/management/commands/load_table.py
- DataRepo/utils/compounds_loader.py
- DataRepo/utils/exceptions.py
- DataRepo/utils/loader.py
- DataRepo/utils/protocols_loader.py
- DataRepo/utils/study_table_loader.py
- DataRepo/utils/tissues_loader.py
- Added calls to self.errored() wherever there is a continue due to the return of is_skip_row()
- Added a skipped() method and stat (for when a record is not attempted to have been loaded because data for a previous model record had an issue
- Added a num argument to the incrementors, specifically for incrementing all synonyms parsed from a line when skipped.
- Buffered RequiredColumnValue from inside get_row_val because it was unintentionally stopping the loop.
- Fixed the summarization code in ConflictingValueErrors.
- Improved the summarization code to group by file and list associated row numbers.
- Resolves #863
- Review …
> Fixed minor bugs in stats reporting and conflicting value error summarization (mainly for compounds)

- .gitignore
- CONTRIBUTING.md
- DataRepo/management/commands/load_compounds.py
- DataRepo/management/commands/load_sequences.py
- DataRepo/management/commands/load_study_table.py
- DataRepo/management/commands/load_table.py
- DataRepo/management/commands/load_tissues.py
- DataRepo/tests/loading/test_load_table.py
- DataRepo/tests/loading/test_loading_protocols.py
- DataRepo/utils/compounds_loader.py
- DataRepo/utils/exceptions.py
- DataRepo/utils/file_utils.py
- DataRepo/utils/loader.py
- DataRepo/utils/protocols_loader.py
- DataRepo/utils/study_table_loader.py
- DataRepo/utils/tissues_loader.py
Added the ability to read default values from an excel sheet.
Details and miscellaneous updates:
- Replaced unused variables with underscores
- Removed pointless constructors in derived classes
- Made load_wrapper pass along arguments (if any).  (Note, there is commented code that needs to be removed in there.)
- There are some debug prints that need to be removed.
- Added method get_user_defaults to TraceBaseLoader
- Made df an optional argument to the traceBaseLoader constructor in order to be able to optionally supply it to load_data and make it easier to set defaults via the constructor.  (Headers need to be set before that dataframe could be used anyway - it just makes sense to hold off on setting it until it's ready to be processed.  And if it's supplied, it potentially could be …
> Sequence load 1a (read a defaults sheet)

- DataRepo/management/commands/load_compounds.py
- DataRepo/management/commands/load_protocols.py
- DataRepo/management/commands/load_sequences.py
- DataRepo/management/commands/load_study_table.py
- DataRepo/management/commands/load_table.py
- DataRepo/management/commands/load_tissues.py
- DataRepo/tests/loading/test_load_table.py
- DataRepo/tests/loading/test_loading_protocols.py
- DataRepo/tests/utils/test_loader.py
- DataRepo/utils/compounds_loader.py
- DataRepo/utils/loader.py
- DataRepo/utils/protocols_loader.py
- DataRepo/utils/sequences_loader.py
- DataRepo/utils/study_table_loader.py
- DataRepo/utils/tissues_loader.py
Renamed most of the (abstract) class attributes and moved class attributes from LoadFromTableCommand to TraceBaseLoader.
The class attribute names became somewhat ambiguous when the defaults sheet was introduced, so not all attributes that are about the input data sheet start with "Data" and all the ones for the defaults sheet start with "Defaults".
I also realized that details of the files (e.g. headers) were a part of the loader class(es), so I decided that the sheet names should live there as well.  Now the only class attribute in LoadFromTableCommand is loader_class.
As such, I also moved the protocol alternate excel file headers definition to the ProtocolsLoader and adjusted the logic for set_headers in the superclass when the loader object is recreated so that "saved" headers would …
> Sequence load 2 (renames and code moves)

- DataRepo/utils/__init__.py
- DataRepo/utils/accucor_data_loader.py
- DataRepo/utils/compounds_loader.py
- DataRepo/utils/protocols_loader.py
- DataRepo/utils/sequences_loader.py
- DataRepo/utils/study_table_loader.py
- DataRepo/utils/tissues_loader.py
- DataRepo/views/__init__.py
This implements the atomic transaction TODO item in the sequence load PR series.  This resolves an unrealized concern about the nature of the `AggregatedErrors` strategy, where exceptions are allowed to happen and processing of an input file is allowed to continue despite those exceptions (which are buffered and the code is allowed to proceed).
In a discussion I had on the django forum about a different but related issue, I realized that I had been mis-interpreting what I would consider ambiguous language in the django docs about what to do in the event of database-related exceptions.  I had interpreted the language about catching and rolling back in another try/except block to be referring to an *outer* block, when allowing the code to proceed, making things safe.  But I learned that …
> Atomic transactions added to new loaders

- DataRepo/utils/file_utils.py
Made the presence of the row keys optional in get_column_dupes in order to avoid KeyErrors.  This was the original intention, but the presence of the key wasn't checked before indexing.
- Next PR: #896
I still have not yet figured out how to break up large-ish efforts into a series of PRs.  I just finished an effort and am going about breaking it up into separate PRs.  I'm doing it a bit differently this time, to avoid reviewing rewritten code.  It is slightly complicated by the solution I arrived at to resolve a circular import (another file re-arrangement).
The work in this very small PR addresses KeyErrors that arose because of the way the unique column constraints traversed the row data.  The new load script utilized mutually optional/required columns that had not …
> Made row keys optional in the unique column constraint check

- DataRepo/loaders/accucor_data_loader.py
- DataRepo/loaders/table_loader.py
- DataRepo/tests/utils/test_exceptions.py
- DataRepo/utils/exceptions.py
A lot of the exception code was repetitive.  All of the exceptions that were using `generate_file_location_string` and `summarize_int_list` were modified to inherit from a new base exception class named `InfileError`.
A feature was added to the base class to be able to manually specify where location information should be incorporated into a supplied message.  This is achieved with an "order" argument that corresponds to what information should be placed where formatting "" characters are in the supplied message.
I also noted that a number of the exception tests were put in the wrong test class, so I rearranged them to be in the appropriate classes.
I also created a new exception class named CompoundDoesNotExist in order to provide file context to the exception.
- …
> Improved exception inheritance

- DataRepo/loaders/compounds_loader.py
- DataRepo/loaders/protocols_loader.py
- DataRepo/loaders/sequences_loader.py
- DataRepo/loaders/study_table_loader.py
- DataRepo/loaders/table_loader.py
- DataRepo/loaders/tissues_loader.py
- DataRepo/tests/loaders/test_protocols_loader.py
- DataRepo/tests/loaders/test_table_loader.py
- DataRepo/tests/management/test_load_table.py
This code change is used in the tracers loader that will be in the next PR.
Basically, I changed:
- `TableLoader.DataRequiredHeaders`
- `TableLoader.DataRequiredValues`
from `namedtuple`s to (N-dimensional) lists of required header keys.
The simplest example:
```
[a, b, [c, d]]
```
This means a, b, and (either c or d) are required.
The methods which handle these data structures are recursive and each iteration alternates between "all required" (i.e. "and'ed" groups) and "any required" (i.e. "or'ed" groups).  So, for example:
```
[a, [b, [c, d]]]
```
means "a and (either b or (c and d)) are required".
This makes checking required headers and/or values as simple as just creating the nested list in the derived loader class.
- Merges into PR #898
- Next PR: #900
I …
> Made it possible to define conditionally required columns and column values

- DataRepo/forms.py
- DataRepo/templates/DataRepo/validate_submission.html
- DataRepo/views/upload/validation.py
- static/css/drop_area.css
- static/css/hierarchical_formsets.css
- static/js/file_list_drop_area.js
This only adds the ability to **submit** mzXML file names (via drag and drop) on the validation page.  It also makes the sample table an *optional* field and adds a `clean` method to the form class to require at least 1 file (sample or peak annotation) and, if mzXMLs are provided, a single peak annotation file.
This work explicitly does *not* implement (in order to present small PRs for quick/small reviews):
- processing of those names
- any other changes to the validation form (e.g. submitting one at a time - though it does require only 1 if mzXMLs are provided)
- Partially addresses #888
- Next PR: #919
- `1.` **CURRENT PR:** Integrate the changes in the `dropzone_paths` branch into the Validation Interface to be able to take an mzXML file …
> Added the ability to submit mzXML file **names** on the validation page

- DataRepo/loaders/accucor_data_loader.py
- DataRepo/tests/views/upload/test_validation.py
- DataRepo/views/upload/validation.py
- Added get_approx_sample_header_replacement_regex which returns a regex to heuristically convert common sample headers into database sample names.
- Added build_lcms_dict to turn sample headers from a peak annotation file and mzXML file names into an LCMS dict keyed on the unique header name and containing dicts whose keys are headers of the LCMS metadata format.
- Modified form_valid to call build_lcms_dict with the appropriate arguments.
- Created a class attribute to hold common header suffixes.
- Modified set_files to build the file names if not supplied.
- Added tests for the new methods.
- Partially addresses #829 
- Partially addresses #888
- Merges into #918
- Next PR: #922
author …
> Added a method to create the sample and header data in a dict

- DataRepo/forms.py
- DataRepo/templates/DataRepo/validate_submission.html
- DataRepo/tests/utils/test_exceptions.py
- DataRepo/tests/views/upload/test_validation.py
- DataRepo/utils/exceptions.py
- DataRepo/views/upload/validation.py
This was mainly to remove the mzXML while retaining other related improvements made in the previous PRs, but I also, in the process, worked toward both:
1. Retaining code that I think will be used again, (once the LCMS sheet(s) have a loader), and...
2. Experimenting with an error strategy (a minor amount of effort) that I believe will be much easier for the user to consume (in the form of errors attached to spreadsheet cells via comments).  It was necessary for me to be able to structure the sample sheet excel file creation code in a scalable way.  I needed to see my idea in practice to understand it better, and to plan out the structure of the code in that next step.  These changes may be removed.  I only did a small portion relevant to the lcms code modifications to extract mzXMLs as a …
> Removed mzXML file form field and lcms tsv download

- DataRepo/forms.py
- DataRepo/loaders/accucor_data_loader.py
- DataRepo/templates/DataRepo/validate_submission.html
- DataRepo/tests/loaders/test_accucor_data_loader.py
- DataRepo/tests/test_views.py
- DataRepo/views/upload/validation.py
- Improved the form's clean method so that errors would be associated with their fields.
- Added a check to the form's clean method to ensure that the files are excel and that the peak annotation files were specifically either accucor or isocorr (individually).
- Changed the order of the set_files args and made the sample arg optional.
- Added methods: is_accucor and is_isocorr to the AccucorDataLoader class.
- Changed the way things were imported from django.forms so that it would look cleaner.
- Merges into PR #924
- Next PR: #925 …
> Changed the accucor and isocorr validation file fields into a single field

- DataRepo/loaders/table_loader.py
- DataRepo/management/commands/load_study.py
- DataRepo/tests/loaders/test_table_loader.py
- DataRepo/tests/views/upload/test_validation.py
- DataRepo/views/upload/validation.py
I realized that a number of methods were converting back and forth between dataframes and dicts and I realized that it would all be much easier if I save the production of actual dataframes until after the samples (etc) have been added.
So I converted all instances of `dfs_dict` from a `dict of pandas dataframes` to a `dict of pandas' style dicts`, e.g. `{"columnname": {0: "row 1 value", 1: "row 2 value"}}`.
This prevents the necessity of various methods converting back and forth between dataframes and dicts.  It also addresses issues of places where I was temporarily using lists instead of pandas' version of lists (dicts keyed by sequential integeras starting from 0).
- Resolves no issue, but related to #829
- Merges into PR #930
- Next PR: #932
This pull request …
> Revised how dataframes are stored for efficiency

- DataRepo/loaders/compounds_loader.py
- DataRepo/loaders/protocols_loader.py
- DataRepo/loaders/sequences_loader.py
- DataRepo/loaders/study_table_loader.py
- DataRepo/loaders/table_column.py
- DataRepo/loaders/table_loader.py
- DataRepo/loaders/tissues_loader.py
- DataRepo/tests/loaders/test_table_column.py
- DataRepo/tests/loaders/test_table_loader.py
- DataRepo/tests/management/test_load_table.py
- DataRepo/tests/views/upload/test_validation.py
- DataRepo/utils/exceptions.py
- DataRepo/views/upload/validation.py
In preparation for the other plans for the excel file export and the submission process in general, I also implemented a way to store numerous pieces of metadata associated with excel sheets/columns that are collectively used to build comments, among other things.  Much of the data is derived from the models saved in the loader classes.
Details:
- `validation.py`
- Added methods:
- `get_sample_header_metadata`
- `get_animal_header_metadata`
- `samples_sheet_metadata`
- `animals_sheet_metadata`
- `header_to_cell`
- Added attributes to the `DataValidationView` class:
- `SampleColumns`
- `AnimalColumns`
- `SAMPLE_HEADS`
- `exceptions.py`
- Added class: ConditionallyRequiredOptions
- `table_loader.py`
- Added a new abstract attribute to `TableLoader`: `DataColumnMetadata`, which is a …
> Added comments to the excel headers

- DataRepo/templates/DataRepo/search/results/peakdata.html
Copied the code from the `PeakGroups` results and changed the variable names.
- Resolves #746
746 was already "resolved".  I had just noted that it wasn't linked like it was in the PeakGroups results.
> Linked the treatment in the PeakData advanced search results

- DataRepo/loaders/tracers_loader.py
- DataRepo/tests/loaders/test_tracers_loader.py
Added a tracers loader and associated tests.
Either individual column data (compound, element, mass number, count, and positions) or tracer name is required.  There is also a tracer number column (to associate multiple rows with different isotopes for the same tracer), but if you just supply tracer name, you don't need it, and in both cases, it is never added to the database.
Note that the intention is to make it easier to construct tracers without worrying about formatting, as some users have had difficulty with the formatting of tracer names.  This will dovetail with an excel(/google sheet) formula I created to automatically construct the name, so that users will see the construction of the name as they add data.
Also note that the plan is to pre-populate all tracers in the tracers tab …
> TracersLoader

- DataRepo/loaders/accucor_data_loader.py
- DataRepo/tests/loaders/test_accucor_data_loader.py
- DataRepo/utils/exceptions.py
Adds a function that detects the DataFormat of a peak annotation file.
- Resolves #958
> Add function to detect peak annotation DataFormat

- DataRepo/models/archive_file.py
- DataRepo/tests/loaders/test_msruns_loader.py
- DataRepo/tests/models/test_archive_file.py
Pretty braindead code change.  No explanation necessary.
- Resolves issue with the MSRunsLoader where it wasn't saving the mzXML files.
> Save the mzXML file in the archive, duh

- DataRepo/loaders/msruns_loader.py
- DataRepo/utils/exceptions.py
This was the direction I started in WRT #976.  I basically was cleaning up the `get_msrun_sequence` method and cleared up some of the `if` conditionals that did not previously distinguish between lines from the input file that had no sequence name versus mzXML file loads that were not present in the infile.  In fact, then code originally was written to avoid potential errors from the sequence defaults provided on the commentd line if in fact the defaults were not actually needed (i.e. everything was provided with values in `--infile`).
While I was at it, I finished a half-assed attempt I had never completed due to a change in direction: and that was the ability to supply only *some* of the options: `--instrument`, `--operator`, `--date`, and `--lc-protocol-name`.  I'd realized part-way …
> Improvements to MSRunsLoader.get_msrun_sequence.

- DataRepo/models/archive_file.py
- DataRepo/tests/models/test_archive_file.py
`ArchiveFile` now has a post_delete signal that queues up a `transaction.on_commit` signal for every record that is deleted.  It deletes the file from the archive directory using those signals, but it won't do the deletion if there's an exception before it leaves its atomic block.
This also moved the test of `get_or_create` into a new test class that inherits from the new `TracebaseArchivetestCase` and tests if files are actually created.  If we don't keep the `post_delete` cleanup of the archive, we should edit this to keep that moved test.
- No changes …
> Added the ability for ArchiveFile to clean up the archive after the commit of a delete.

- DataRepo/loaders/msruns_loader.py
- DataRepo/tests/loaders/test_msruns_loader.py
This code buffers created `ArchiveFile` records and very cautiously deletes the files in the archive that were created in the event of a rollback.
The issue originally was to only exit if the default sequence records could not be found, but I quickly realized that there are all sorts of common exceptions that could happen and leave behind orphaned files: missing sample record (very common), missing sequence detailed in the infile (common), duplicates, missing headers... the list goes on and on.  And when I started thinking about having the add a front-loaded loop to handle the infile exceptions for missing sequence records, I started to think of the strategy and eventually creating messy spaghetti code, so I decided a cleaner solution was to simply rollback the directory using a buffer of …
> Msruns loader rollback cleanup

- DataRepo/models/fcirc.py
- DataRepo/tests/models/test_fcirc.py
Caught a situation where the `Animal.last_serum_sample` maintained field value can be invalid due to manual data manipulation and added an error status with a message suggesting that maintained fields be rebuilt.
While I was at it, I addressed a TODO item in the same serum_validity code:
> `TODO: MSRunSequence.date can no longer be null, so these warnings can probably be removed`
An example of the exception previously encountered is in the issue's current behavior section.  This is now what the user gets from this PR when the maintained field value is incorrect:
This is what caused the exception to occur:  The `last_serum_sample` should be on dev, which is still what it is in my sandbox:
```
In [1]: from DataRepo.models import Animal
In [2]: anml = Animal.objects.get(name="20220818M1")
In …
```
> Gracefully handle stale maintained `Animal.last_serum_sample` maintained field

- DataRepo/management/commands/rebuild_maintained_fields.py
Disable caching during maintained field rebuild.  Also clears all cache after a rebuild.
I used this branch to fix stale maintained fields on dev in 4 minutes.  Before this change, the script ran all day and everything rolled back when my GlobalProtect session went stale.  The maintained field values had somehow gotten cleared out when we were mucking with the database manually a few days ago, and this fixed them all (6,310 field values).
- Indirectly related to #985 - makes `rebuild_maintained_field` multiple orders of magnitude faster, with the side-effect of deleting all cached values
- Minimum …
> Disable caching during maintained field rebuild

- DataRepo/loaders/__init__.py
- DataRepo/loaders/msruns_loader.py
- DataRepo/loaders/sample_table_loader.py
- DataRepo/loaders/sequences_loader.py
- DataRepo/management/commands/load_study.py
- DataRepo/models/archive_file.py
- DataRepo/models/compound.py
- DataRepo/models/hier_cached_model.py
- DataRepo/models/infusate.py
- DataRepo/models/peak_group.py
- DataRepo/models/researcher.py
- DataRepo/tests/loaders/test_msruns_loader.py
- DataRepo/tests/loaders/test_sequences_loader.py
- DataRepo/tests/management/test_load_msruns.py
- DataRepo/tests/management/test_load_protocols.py
- DataRepo/tests/models/test_compounds.py
- DataRepo/tests/models/test_hier_cached_model.py
- DataRepo/tests/models/test_researcher.py
- DataRepo/tests/test_models.py
- DataRepo/tests/utils/test_exceptions.py
- DataRepo/utils/exceptions.py
- DataRepo/views/upload/validation.py
The MSRunsLoader was updated to add a method for the PeakAnnotationsLoader to retrieve the MSRunSample records associated with samples gotten from peak annotations files. The ability to skip samples was added, and updates were made to the associated MSRunSequence loader.
Exceptions were also improved to take advantage of the new summarizable errors, so that missing samples and MSRunSample records could be summarized without custom code needed in the loaders.  This included various sample errors and researcher wanrings.
Details:
- MSRunsLoader (TableLoader)
- Data files where I added a "Skip" column (looks to be none??)
- MSRunSequencesLoader
- Researcher (could_be_variant_researcher & get_researchers)
- Exceptions:
- MzxmlSampleHeaderMismatch
- RecordDoesNotExist
- MissingRecords
- …
> PeakAnnotationsLoader 2 - MSRunsLoader updates

- DataRepo/loaders/base/converted_table_loader.py
- DataRepo/tests/loaders/test_samples_loader.py
- DataRepo/tests/loaders/test_sequences_loader.py
- DataRepo/tests/loaders/test_study_loader.py
- DataRepo/tests/loaders/test_tracers_loader.py
- DataRepo/tests/management/commands/test_load_msruns.py
- DataRepo/tests/management/commands/test_load_study.py
- DataRepo/tests/utils/test_exceptions.py
- DataRepo/tests/utils/test_file_utils.py
- DataRepo/tests/views/upload/test_validation.py
In order for `ConvertedTableLoader` to be used to convert the study doc, it needs to output more than a single dataframe.  These are the changes necessary to support outputting a dict of dataframes.
Note, much more would need to be done to fully support this.  It was done mostly using overridden methods in derived classes, but in order for this to interact well with `TableLoader`, a few changes were necessary.
- Partially addresses #1032
- Partially addresses #1041
- Partially addresses #1048
- Partially addresses #839
- Merges into PR #1065
- Next PR: #1067
- …
> `V3 Loading PR Series #3`: Added support to `ConvertedTableLoader` to support conversion of the old study doc to the new version

- DataRepo/loaders/animals_loader.py
- DataRepo/loaders/lcprotocols_loader.py
- DataRepo/loaders/peak_annotation_files_loader.py
- DataRepo/loaders/studies_loader.py
- DataRepo/management/commands/load_samples.py
- DataRepo/management/commands/load_table.py
- DataRepo/models/researcher.py
- DataRepo/tests/loaders/test_study_loader.py
- DataRepo/tests/loaders/test_tracers_loader.py
- DataRepo/tests/management/commands/test_load_study.py
- DataRepo/tests/views/upload/test_validation.py
Fixed issues in the animals, lcprotocols, annotation files, and studies loaders, along with the load samples script, the load table superclass, and minor changes to the researcher class.
Details:
- Added the anonymous researcher check to could_be_variant_researcher().
- Move the file is None check to above the dtypes setting, to avoid an exception in load_table.
- Added the ability to set a custom defer_rollback in load_table.
- Streamlined the initialization of the loader_class in load_table.
- Added a legacy option to load_samples so I can catch every attempt to use it as if it was the old script and issue the appropriate error.
- Corrected the required values in the studies loader to just the name.
- Fixed an issue in the peak annotation files loader to not try and load when the file …
> `V3 Loading PR Series #6`: Miscellaneous small loader fixes

- DataRepo/loaders/infusates_loader.py
- DataRepo/loaders/tracers_loader.py
- DataRepo/models/infusate.py
- DataRepo/models/tracer.py
- DataRepo/models/tracer_label.py
- DataRepo/tests/loaders/test_study_loader.py
- DataRepo/tests/management/commands/test_load_study.py
- DataRepo/tests/views/upload/test_validation.py
- DataRepo/utils/infusate_name_parser.py
Fixes to tracer and infusate name processing.
Details:
- Added the ability of parse_infusate_name_with_concs to strip the unparsed tracer string of white spaces at the ends, which was causing matching issues when comparing it to database generated names.
- In each of the models (Infusate, Tracer, and TracerLabel), I added a name_from_data method to be able to generate their names using the data objects as a complement to the database method so that the database name and the parsed/submitted name could be compared without having issues WRT the compound synonym used or the order of the tracers or labels.
- Also added a name_with_synonym method to the Tracer model for the same reason as above.
- Modified code in the Infusate model that checks the supplied infusate name/data to be able to …
> `V3 Loading PR Series #7`: Infusate and tracer name validation and processing fixes

- DataRepo/loaders/study_loader.py
- DataRepo/management/commands/load_study.py
- DataRepo/tests/views/upload/test_validation.py
- DataRepo/views/upload/validation.py
Added the ability for StudyLoader to convert study docs from the previous format to the current format.
This change was the driver for addressing all of the exceptions that caused issues with the validation interface, because it instantly allowed me to test the interface with all the data from the Rabinowitz repo, so it essentially saved me a lot of time manually converting all the old study docs.
Technical git note, this includes the file `load_study.py` which I found out when testing this branch that I had accidentally removed it from this series of branches due to an incorrect attempt to fix the fact I'd accidentally added it to one of the first commits during cherry picking.
Details:
- StudyLoader now inherits from ConvertedTableLoader instead of TableLoader.
- Added derived classes …
> `V3 Loading PR Series #8`: Backward study doc compatibility

- DataRepo/loaders/msruns_loader.py
- DataRepo/management/commands/load_msruns.py
- DataRepo/tests/loaders/test_msruns_loader.py
This adds the ability for the msruns loader to equate peak annotation sample headers with mzXML file names if they differ by dashes and underscores.
An option to only allow exact matches can revert to the original behavior.
- Resolves #991
- Merges into: #1079
- Next PR: #1081
I originally branched this off main, but I needed fixes in the outstanding PRs to be able to test using the submission interface. …
> Match underscores in sample headers with dashes in mzXMLs

- DataRepo/loaders/msruns_loader.py
- DataRepo/tests/loaders/test_msruns_loader.py
When working on the previous 2 PRs, I was testing with this isoautocorr sample data: [col013a_tracebase_studydoc.xlsx](https://github.com/user-attachments/files/16474172/col013a_tracebase_studydoc.xlsx).
The samples use dash delimiters instead of underscores, and the scan labels were in the middle of the sample names, so even though, for example `His-neg-M3-T02-liv` and `His-pos-M3-T02-liv` were from the same sample (and were just different mzXML files), they would be generated as different samples in the database, which we don't want.
This happens because the heuristic used up until now required the scan labels to be suffixes and for the delimiters to be underscores.
This PR updates the heuristic to allow dashes as delimiters and for the scan label to be anywhere inside the sample …
> Changed sample name derivation heuristic from suffix to internal scan labels

- DataRepo/loaders/peak_annotations_loader.py
- DataRepo/tests/loaders/test_peak_annotations_loader.py
- DataRepo/views/upload/validation.py
Made dramatic running time improvements to the autofill-only mode of the build-a-submission page (when numerous compounds don't exist in the database).
It turns out that there were a number of aspects of the code that, when these combined changes are implemented, there is a dramatic improvement to data-specific lag (e.g. when there are numerous repeated lookups of missing compounds).
One thing I learned during this effort is that pandas' `iterrows` method is very slow.  So when the peak annotations file is large (many samples and many compounds), the unicorr format has the drawback that it hits pandas' iterrows pretty hard.  The time that pandas spends instantiating pd.Series objects becomes rather large.  I had initially just mimicked existing code when I utilized iterrows, so I imagine …
> Sped up the submission page autofill when numerous compounds are missing

- DataRepo/views/upload/submission.py
Suppressed errors about missing peak annotation files when validating only the study doc.
You can test with [MASTER STUDY DOC FOR TRACEBASE_exp011b3_240816.xlsx](https://github.com/user-attachments/files/16662101/MASTER.STUDY.DOC.FOR.TRACEBASE_exp011b3_240816.xlsx).  It produces lots of errors, but `FileFromInputNotFound` is no longer one of them.
- Resolves #1169 …
> Suppress errors about missing peak annotation files during study-doc only validation

- DataRepo/loaders/msruns_loader.py
Removed circular conditional logic that was preventing clean-up of created archive files upon exception.
- Resolves #990
> Archive cleanup exception fix

- DataRepo/loaders/infusates_loader.py
- DataRepo/views/upload/submission.py
Fixed an uncaught exception related to a missing infusate row group value and handled a rollback exception related to that missing value.
Details:
- Instead of checking if the row group number was `None`, I checked if its str cast was in none_vals.
- Added an atomic transaction decorator to get_or_create_infusate_tracer, made it raise a RollbackException, and caught it in the calling method.
- Resolves #1166
- Associated …
> Uncaught Exception related to missing required row group value

- DataRepo/loaders/msruns_loader.py
- DataRepo/loaders/study_loader.py
- DataRepo/tests/loaders/test_study_loader.py
- DataRepo/tests/views/upload/test_submission.py
- DataRepo/views/upload/submission.py
Fixed an uncaught exception on the validate page when an invalid study doc is submitted.
It turned out that I had overlooked the removal of one of the `dfs_dict_is_valid` calls.  It could be that the existing call was (re-)introduced by a maerge, but regardless, the validation is not handled by the study_loader, which buffers errors about missing or unexpected columns.
I also neglected to call `create_study_dfs_dict` and supply it the dict derived from the uploaded file.  It has the ability to add missing sheets and columns, and when I created the validate page (and the start page), I had made changes to statically set the mode (autofill or validate), and in doing so, I should have realized that in validate mode, I needed to call that method.  I renamed the method to …
> Fixed an uncaught exception on the validate page

- DataRepo/views/upload/submission.py
The issue mentions adding "all compounds", but given Michael's concern about identifying the compounds from the peak annotation files and the large number of compounds in tracebase, I decided to only add those with matching formulas, which should both be easier for the researcher to pour through and remain scalable as tracebase grows.
That also solves the original problem, which was there was no way to add a missing synonym if the compound to add it to wasn't present in the sheet.
- Resolves #1153 …
> Added compounds with matching formulas to the Compounds autofill

- DataRepo/loaders/base/table_loader.py
- DataRepo/loaders/study_loader.py
- DataRepo/management/commands/load_study.py
- DataRepo/models/hier_cached_model.py
- DataRepo/tests/loaders/test_study_loader.py
- DataRepo/tests/management/commands/test_load_table.py
Been working on Michael's water study.  Fixed all the issues using the validate page and tried running `load_study` on the command line on dev.  Turns out that there was a bug with dry-run mode (which I tried first).  It was running each child loader in dry-run, which was wrong.  Only the outer loader `StudyLoader` should run `load_data` in dry-run and defer rollback exceptions until all child loaders are done, THEN raise the DryRun exception inside the outer atomic transaction block.
- Merges into PR #1175
- All blocking issues …
> Fixed dry-run mode in `load_study`

- DataRepo/loaders/base/table_loader.py
- DataRepo/loaders/peak_annotation_files_loader.py
- DataRepo/loaders/study_loader.py
- DataRepo/management/commands/load_table.py
- DataRepo/tests/loaders/base/test_table_loader.py
While working on Michael's water study, I wanted to see how many compound and synonym records were being created, but when I ran `load_study` in dry-run mode on an excel file containing only the Compounds sheet, there were no stats - just the dry run complete message.  I quickly realized that this is because the stats are not accumulated from the nested loader calls.  This PR adds that ability to accumulate stats from each loader call, so that now at the end of a `load_study` call, (for a compounds only load), you get something like this:
Added the ability to track load stats of calls to nested loaders.
Details:
- Checked the outer loop from using self.loader_class.get_models to using load_stats.keys()
- Added method to TableLoader: update_load_stats, to sum stats from different loaders. …
> Load stats improvement

- DataRepo/loaders/base/table_loader.py
- DataRepo/loaders/peak_annotations_loader.py
- DataRepo/loaders/study_loader.py
- DataRepo/models/peak_group.py
- DataRepo/tests/loaders/test_msruns_loader.py
- DataRepo/tests/loaders/test_study_loader.py
- DataRepo/tests/management/commands/legacy/test_load_accucor_msruns.py
- DataRepo/tests/management/commands/test_load_peak_annotations.py
- DataRepo/tests/models/test_peak_group.py
- DataRepo/tests/views/upload/test_submission.py
- DataRepo/utils/exceptions.py
- DataRepo/utils/infusate_name_parser.py
Fixed various issues revealed by Michael's water study that were preventing loading and making error navigation difficult.
Details:
- Made the `MultiplePeakGroupRepresentations` error not inherit from `ValidationError`
- Added a check for `NoTracerLabeledElements` in `PeakGroup.clean()`
- Added a check for `NoTracers` in `PeakGroup.clean()`
- Created `PeakGroup.check_for_multiple_representations()` to encapsulate the logic.
- Created an override of `PeakGroup.save()` to check for multiple representations (because otherwise, a cryptic `IntegrityError` results).
- Resolves #1194
- Resolves #1189
- Merges into main (previously merged into PR #1190)
author and/or reviewers should uncheck any …
> Fix for un-raised `MultiplePeakGroupRepresentations` errors and made `NoTracerLabeledElements` a warning/skip

- DataRepo/data/tests/multiple_representations/mult_reps.tsv
- DataRepo/loaders/peak_annotations_loader.py
- DataRepo/loaders/peak_group_conflicts.py
- DataRepo/models/peak_group.py
- DataRepo/tests/loaders/test_peak_group_conflicts.py
This implements a processing of the solution proposed to eliminate the need to edit peak annotation files.  This defines the Peak Group Conflicts sheet and processes that sheet to check for errors and return the data in a dict necessary to load only selected compounds among multiple representations.  Note, this is only part of the solution.  I'm breaking up the effort.
- Partially addresses #1199
- Associated issue/pull request …
> Class to process researcher selections for multiple representations

- DataRepo/forms.py
- DataRepo/management/commands/profile_submission_page.py
- DataRepo/models/msrun_sequence.py
- DataRepo/templates/submission/includes/1_start.html
- DataRepo/templates/submission/includes/3_validate.html
- DataRepo/templates/submission/submission.html
- DataRepo/tests/views/upload/test_submission.py
- DataRepo/urls.py
- DataRepo/utils/file_utils.py
- DataRepo/views/__init__.py
- DataRepo/views/upload/__init__.py
- DataRepo/views/upload/submission.py
- DataRepo/widgets.py
- static/css/tbforms.css
- static/js/submission.js
This is an incremental step toward changing the submission start page to include sequence details for each input peak annotation file.  It replaces the multi-file picker with a single-file picker that will be cloned in javascript using +/- buttons, like in the advanced search.
The resulting start page (temporarily) looks like this:
It implements dropdowns for 3 of the sequence metadata fields, e.g.:
Details:
- Renamed the form and view classes involved from including "validation" to "submission".
- Removed the javascript code that rendered the peak annotation file list (because it will no longer be used).
- Changed the names of the study doc and peak annotation form fields (and made the necessary changes for changing the multi-file picker to a single file picker).  I kept the list …
> Submission flow phase 2 (adding the sequence form fields)

- DataRepo/data/tests/multiple_representations/mult_reps.tsv
- DataRepo/loaders/peak_group_conflicts.py
- DataRepo/tests/loaders/test_peak_group_conflicts.py
Removed the Sequence Name column and added a Common Samples column (along with 2 other metadata columns for sample count and a short set of example samples).
This supports only 1 peak group compound representation per sample as opposed to 1 per sample and sequence.  I could have left sequence and made it a delimited column, but decided that I could add it back later.  Right now, the priority is the basic functionality.
I changed the returned dict to be keyed on individual sample name instead of the combo and instead of the sequence.  It will make the lookup easier.
I intend to hide the common samples column, because it will be a mess to look at for the user, but it's utility is for the unique constraint (and to support multiple sequences in a file with difference sets of samples).
Files …
> Removed the sequence from the multiple representation choice logic

- DataRepo/loaders/base/table_loader.py
- DataRepo/loaders/peak_group_conflicts.py
- DataRepo/loaders/study_loader.py
- DataRepo/tests/loaders/test_study_loader.py
- DataRepo/tests/views/upload/test_submission.py
- DataRepo/views/upload/submission.py
Create and autofill the peak group conflicts sheet.
~Unfortunately, while this works, it triples the amount of time it takes to process peak annotation files, but I decided to check in this working version and then try and optimize it, perhaps using pandas operations on the data instead of loops...~ Added running time is now negligible.  I optimized it in the last commit, though I'm not sure how it will behave when adding to a study, but I can say that if the study does not exist in the DB, this adds virtually no time.  The largest study now finishes in about 45s.
Details:
- Added the PeakGroupConflicts loader and sheet to the BuildSubmissionView.
- Added the ability to autofill 1-cell dropdowns from the autofill_dict by setting the autofill value to the dict needed by xlsxwriter's …
> Submission start - Create and autofill the peak group conflicts sheet

- DataRepo/models/maintained_model.py
During the work on `clean_reps` in #1167, I discovered that I needed the return value of decorated methods, and the `MaintainedModel` decorators weren't passing the return value(s) along, so I added that, and I added more/better suggestions in the `AutoUpdateFailed` exception.
> Added returns of decorated methods and added suggestions to the `AutoUpdateFailed` exception

- DataRepo/loaders/msruns_loader.py
- DataRepo/utils/exceptions.py
Addressed exceptions I ran into while trying to load Michael's water study mzxml files.
Details:
- Prevented any error when the file contains no scans.
- Fixed issues related to skipping mzXML file loads.
We do not anticipate the user to fill out the mzXML file name column in the Peak Annotation Details sheet (though it's there in case the name doesn't match the sample header or when disambiguation is necessary in the face of same-named files.  This means that the skipping of files for skipped sample headers needs to account for the fact that the files can have the same name and are thus stored in a dict that includes the directories.  The way it was written, it would only skip files whose paths were provided in the Peak Annotation Details sheet, thus this PR adds code that makes an …
> Fixed `mzXML`-related exceptions related to walking the directory to find all `mzXML` files

- DataRepo/templates/DataRepo/search/results/peakdata.html
- DataRepo/templates/DataRepo/search/results/peakgroups.html
- The peak data format now has visible peak annotation filenames.
- The Labeled Element column in the PeakGroups format no longer causes an exception.
- Resolves #1252
- Resolves #1253
- Merges into PR #1251
> Fixed a couple of advanced search template typos

- DataRepo/loaders/base/table_loader.py
- DataRepo/loaders/msruns_loader.py
- DataRepo/management/commands/load_msruns.py
- DataRepo/management/commands/load_table.py
- DataRepo/tests/management/commands/test_load_msruns.py
- DataRepo/utils/exceptions.py
I didn't know what was causing `mzXML` files to not get added to newly created `MSRunSample` records, so my first hunch was that it had to do with the fact that the `mzXML`s couldn't be linked to a row in the file due to the fact that there were more mzXMLs than there were rows.  That issues was caused by the fact that there exist empty `mzXML` files that are byproducts of the process that generates them.  I figured if I could skip these empty `mzXML`s, then the method that links rows (containing the necessary sequence info needed to create `MSRunSample` records) to files would work and would then create the records.  Ultimately, as a product of this effort, I figured out the real cause of the problem (which was not this issue), but this effort does dramatically reduce the warning output …
> Skip empty mzxmls

- DataRepo/loaders/peak_annotations_loader.py
- Resolves #1300
- Merges into PR #1301
> A fix to the `Accucor` to `Unicorr` format conversion that caused compounds to get the wrong formula when a `C12 PARENT` row is missing

- DataRepo/loaders/base/converted_table_loader.py
- DataRepo/tests/loaders/base/test_converted_table_loader.py
Conversion of single accucor corrected sheets in csv or tsv format were failing due in part to the ambiguity of the context when dealing with one required sheet or one supplied sheet.  These code changes make a distinction for that context, allowing columns in the one supplied sheet to be condensed ("melted" in pandas' terminology).
- Merges into PR #1308
- Basic …
> Better single sheet handling for csv and tsv format conversions

- DataRepo/loaders/base/converted_table_loader.py
- DataRepo/loaders/peak_annotation_files_loader.py
- DataRepo/tests/loaders/base/test_converted_table_loader.py
There was a `TypeError` exception about the Peak Annotation File column when a row was empty.  I encountered this edge case when converting the fluxomics study to version 3.
All I had to do was check the skip rows in the loop.  The superclass already marks empty rows as skip rows.  I just needed to add a check.
- Merges into PR #1307
- Overhead …
> Skip empty rows in the `PeakAnnotationFilesLoader`

- DataRepo/loaders/base/converted_table_loader.py
- DataRepo/loaders/peak_annotation_files_loader.py
- DataRepo/tests/loaders/base/test_converted_table_loader.py
- DataRepo/tests/utils/test_file_utils.py
- DataRepo/utils/file_utils.py
Empty rows in sheets that have multiple columns involved in a unique constraint were getting `DuplicateValueErrors` buffered when there were empty rows in the sheet:
This fixes the duplicate row detection logic to accurately ignore empty value combinations.
- Merges into PR #1306
> Fixed erroneous duplicate column combo detection for empty columns

- DataRepo/loaders/peak_annotations_loader.py
- DataRepo/tests/loaders/test_peak_annotations_loader.py
This makes a csv or the accucor corrected sheet actually work.
Details:
- A isotopeLabel column is added to the corrected sheet, based on the C_Label column.
- The Original sheet was removed from AccucorLoader.OrigDataRequiredHeaders.
- "formula" is only added to the get_or_create for the PeakGroup model if it has a value.
- medMz, medRt, and formula were removed from the required headers and values of the Unicorr format.
- Merges into PR #1309
- Specific reviewers: …
> Final fix for loading `Accucor` corrected sheets from `csv`

- DataRepo/loaders/peak_annotations_loader.py
- DataRepo/utils/exceptions.py
- DataRepo/views/upload/submission.py
Added identification of an edge case where the user omitted adding a peak for the C12 PARENT when picking peaks.  Michael said that if this is encountered, the researcher must re-pick the peaks to include the C12 PARENT peak.
Details:
- Incorporated exceptions from the PeakAnnotationsLoader into the status of the submission start page.
- Created exception classes: MissingC12ParentPeak and MissingC12ParentPeakErrors (to summarize the exceptions).
- Created PeakAnnotationsLoader.check_c12_parents() and called it from the constructor, to buffer errors about missing C12 PARENT rows and to mark affected rows as skip rows, so that there will not be related multiple representations errors that follow.
- Resolves #1300
- Merges into PR #1314
This pull request will be merged …
> Catch missing C12 PARENT row issues

- DataRepo/loaders/base/converted_table_loader.py
- DataRepo/loaders/base/table_loader.py
- DataRepo/loaders/study_loader.py
- DataRepo/management/commands/load_table.py
- DataRepo/views/upload/submission.py
- Resolves #1299
- Merges into PR #1302
> A fix for running the `AnimalsLoader` from the command line by itself when the animal's `age` is empty

- DataRepo/formats/peakdata_dataformat.py
- DataRepo/formats/peakgroups_dataformat.py
- DataRepo/tests/test_formats.py
Searching for polarity makes no sense.  Every peakgroup and/or peakdata row links to multiple polarities, so it never narrows down the results.  Polarity was thus removed from the dataformats for both of those advanced search views.
- Resolves #1283
> Polarity removal

- DataRepo/loaders/base/converted_table_loader.py
- DataRepo/loaders/peak_annotations_loader.py
- DataRepo/views/upload/submission.py
After this PR, when you submit the carnosine study's accucor files to the submission start page, instead of a 500 error, you get:
- Partially addresses #1320
> Added graceful handling of errors related to peak annotation file conversion

- DataRepo/loaders/infusates_loader.py
Note, this fix does not have to be perfect.  The inclusion of the concentrations in the infusate name will no longer be necessary after the implementation of issue #1053, for which I have a [plan](https://stackoverflow.com/a/79122435/2057516).
- Resolves #1336
> Fixed an Infusate name check to do with significant figures

- DataRepo/loaders/animals_loader.py
- DataRepo/models/animal.py
- DataRepo/tests/loaders/test_animals_loader.py
- DataRepo/tests/utils/test_text_utils.py
- DataRepo/utils/text_utils.py
The problem was caused by the researcher using an excel formula to calculate the infusion rate.  The precision supported by excel had 2 more digits than the database could store, so whenever the record already existed, `get_or_create` would raise a `ConflictingValueError`.
To solve this, instead of calling `get_or_create` with the raw value, I applied `sigfig()` to the value and set the significant figures to 3.  And in order to support previously loaded values (and changes in significant figures in the future, I implemented a query that searches for values that are within the given precision.
Details:
- Added `text_util` methods:
- `sigfigfloor`
- `sigfigceil`
- `sigfigrange`
- Added class attributes to Animal:
- `INFUSION_RATE_SIGNIFICANT_FIGURES`
- `BODY_WEIGHT_SIGNIFICANT_FIGURES`
- …
> Fixed precision issue in the `AnimalsLoader`

- DataRepo/views/upload/submission.py
While converting the example data, I encountered server 500 errors caused by custom header usage.  The submission interface currently only supports default headers and explains them in conversion errors, but the dtype exceptions are separate and only occur if all headers in the dtype dict do not match (which was the case for the Study sheet in one example study).  I added try/catch blocks around each one.
I would eventually like to move the file reading into `TableLoader`, which will eliminate a lot of repeated code here, but this is a quick fix - bigger fish to fry.
- Review …
> Addressed uncaught `InvalidDtypeDict` exceptions on the submission interface

- DataRepo/loaders/infusates_loader.py
This is another issue encountered during conversion of the example data.
And it is another edge case of matching tracer concentrations in the sheet vs in the infusate name (which has significant digits applied).  It prevents this error in the infusates loader, as seen on the validation interface:
This fix is different from the recent `sigfig` strategy.  You can't use `math.isclose` in the DB search.  But it is also another case of making this name match in the past (and a better one).  There's probably a consolidated strategy that could be applied.  I haven't settled on one yet.
- Resolves no documented issue.
- Merges into PR #1357
author and/or reviewers should uncheck any unmet …
> Tracer concentration precision issue fix

- DataRepo/loaders/msruns_loader.py
- DataRepo/loaders/peak_annotations_loader.py
- DataRepo/models/maintained_model.py
- DataRepo/tests/utils/test_exceptions.py
- DataRepo/utils/exceptions.py
- DataRepo/views/upload/submission.py
Miscellaneous small fixes to issues encountered while making changes to accommodate the data in the example studies, so their loads succeed.
Details:
- Removed a duplicate instance of `CompoundsLoader.DataHeaders.NAME` I encountered when simultaneously looking for an issue Michael reported while I was wouking on the contrib doc.  Incidentally, that issue turned out to be user error (me), but also inspired a new feature issue about preserving the Peak Group Conflicts dropdowns when they go through validation.
- Discovered that an exception can arise under the InfileError code when there is a percent sign in the error string.  Fixed one case.  There are likely potentially more, but the problematic feature is planned to be refactored.
- Added a pylint disable that arises in MaintainedModel …
> Misc small fixes

- DataRepo/loaders/samples_loader.py
- DataRepo/loaders/study_loader.py
- DataRepo/tests/loaders/test_samples_loader.py
- DataRepo/tests/utils/test_exceptions.py
- DataRepo/utils/exceptions.py
- DataRepo/utils/file_utils.py
Caught exceptions related to date and duration parsing errors.
Details:
- Cleaned up some docstrings.
- Added a catch of DateParserError in file_utils.py.
- Created exception class DurationError.
- Gated the builtin suggestion in DateParseError to only be present if the string has a number in it.
- Caught date parse errors in the StudyLoader's convert_df code.
- Caught date and duration related errors in the SamplesLoader and streamlined the error text and suggestions.
- Resolves #1343
- Specific …
> Handled uncaught date and duration exceptions

- DataRepo/loaders/msruns_loader.py
- DataRepo/loaders/study_loader.py
- DataRepo/management/commands/export_studies.py
The mzXMLs were not being found when the study doc is supplied without a path (i.e. the path was relative to the current directory.  This fixes that.  I discovered this issue when trying to load the mzXML files for the perturbative infusions study.  The changes that introduced the bug were the recent ones that use the directory that the study doc is in. …
> Study dir empty fix

- TraceBase/settings.py
I have been unsuccessful in figuring out how to reproduce the blocking/timeout behavior.  Nothing I try seems to be able to make it happen - even redoing exactly what I did before when I had encountered it.  There must be some other factor involved that I'm unaware of.  As described in comments in the issue, I will rarely (sometimes) run into a gateway timeout, though when it starts happening, it seems to be reproducible.
During one documented occurrence of the blocking behavior, I proved (during one validation of the cold exposure study doc) that the reason it was taking 7 minutes was due to a blocked query relating to a cache table delete.  I have a separate branch on which I'm working to prevent the cache deletion during a validation or dry-run, which should mitigate the issue.
Since I …
> Set the database "isolation_level" to `REPEATABLE_READ` to prevent gateway timeouts

- DataRepo/formats/dataformat.py
- DataRepo/formats/dataformat_group.py
- DataRepo/templates/DataRepo/search/results/stats.html
- DataRepo/tests/test_formats.py
- TraceBase/.env.example
- TraceBase/settings.py
This is a simple truncation of the loop that counts all the stats.  I'd tried downsampling, but doing that took way longer than just stopping the loop based on the elapsed time.  This is not a perfect solution, but a stop-gap to prevent 500 gateway timeout errors.
The result is that if the calculation of the stats takes over 55 seconds, the loop is stopped and this message appears above the stats presented:
- Resolves #1281
- …
> Added a time limit to the computation of results stats

- DataRepo/tests/views/upload/test_submission.py
- DataRepo/utils/exceptions.py
- DataRepo/views/upload/submission.py
Sample data in the Samples sheet of the study doc was getting overwritten with empty values when the sample record creation had encountered an exception.  Later steps in the MSRunsLoader subsequently raised missing sample exceptions, which was handled by trying to stup out the missing samples in the samples sheet.  That was overwriting the manually entered sample data.  This PR adds a check for the existence of sample data in the sheet before trying to autofill it.
This was apparently an edge case bug that might be related to fixes/changes in the `MSRunsLoader` related to the handling of the missing sample exceptions.  Or it could have existed all along and we just didn't see it due to the fact that other exceptions that would prevent animal or sample record creation had placeholder …
> Fixed sample blanking bug

- DataRepo/loaders/animals_loader.py
- DataRepo/models/infusate.py
- DataRepo/tests/loaders/test_animals_loader.py
This change reduces the number of pages of errors from Edmundo's originally submitted file from 6.5 down to 1 (counting by the number of times you have to hit the page down key):
- Removed the marking of the row as a skip row on the animals sheet when the infusate is not found (since infusate is no longer a required column anyway).  I did not attempt to create a placeholder infusate (e.g. from the name entered into the animals sheet) because there are no other errors it being missing causes (unless performing and actual load of the peak annotation data, which won't occur until this issue is fixed on the website anyway).
- Skipped the buffering of an UnexpectedInput exception about an infusion rate being supplied without an infusate being present (if an infusate name was supplied on that …
> Mitigated a cascade of errors stemming from a mismatched infusate

- DataRepo/data/tests/small_obob2/sample_table_headers_v3.yaml
- DataRepo/data/tests/small_obob2/serum_lactate_sample_table_han_solo_v3.tsv
- DataRepo/loaders/msruns_loader.py
- DataRepo/loaders/peak_annotations_loader.py
- DataRepo/loaders/peak_group_conflicts.py
- DataRepo/management/commands/load_samples.py
- DataRepo/management/commands/load_study.py
- DataRepo/tests/loaders/test_peak_annotations_loader.py
- DataRepo/tests/management/commands/test_load_samples.py
- DataRepo/utils/file_utils.py
The tests for `PeakAnnotationsLoader.is_selected_peak_group` deserved their own PR.  They are an important relatively new feature that I never tested in the tests (just manually with real data).  They turned up a couple minor issues that I was surprised hadn't already been encountered.  I made a couple trivial unrelated changes as well.
- Removed reference to the legacy scripts from load_study and load_samples.
- Removed the TODO comment to remove the associated error code about attempting to use the old interface.  I.e. I decided to keep it.
- Added tests to test every code block of the method: `PeakAnnotationsLoader.is_selected_peak_group` and fixed minor issues the tests uncovered.
- The cases covered by the tests are:
- No Peak Group Conflict exists to check
- A conflict exists but no …
> Batch 8 of legacy loader test updates (tests for `PeakAnnotationsLoader.is_selected_peak_group`)

- DataRepo/loaders/base/table_loader.py
- DataRepo/loaders/msruns_loader.py
- DataRepo/loaders/peak_annotations_loader.py
- DataRepo/utils/exceptions.py
These changes relate to errors I encountered upon attempting to load Edmundo's cystine study **with** his `mzXML` files.  The load was failing and it was due to recent changes that had not been tested against a load that included `mzXML` files.
The main change that prevented the load was the change to make the `RecordDoesNotExist` exceptions to be reported as being from the `mzXML` file instead of from the study doc's `Peak Annotation Details` sheet.  The intention was to disambiguate the source of the exception.  The problem with that was that the `MissingSamples` class that summarizes these exceptions has a documented limitation that all exceptions must be from a single file.  If they aren't, it raises a `ProgrammingError` exception, and that was stopping the load.  And all this was …
> Fixed blocking `ProgrammingError` exception edge case stemming from a recent change

- DataRepo/tests/views/upload/test_submission.py
- DataRepo/views/upload/submission.py
> Raise `PermissionError` if the site is `READONLY`

- DataRepo/loaders/base/converted_table_loader.py
- DataRepo/loaders/peak_annotations_loader.py
- DataRepo/models/peak_group.py
- DataRepo/tests/loaders/test_msruns_loader.py
- DataRepo/tests/loaders/test_peak_annotations_loader.py
- DataRepo/tests/management/commands/test_load_peak_annotations.py
- DataRepo/tests/utils/test_exceptions.py
- DataRepo/utils/exceptions.py
Fixed PeakAnnotationsLoader.check_c12_parents to warn and fix instead of error and skip.
Michael had pointed out in a comment on an issue in the data repo:
http://github.com/PrincetonUniversity/tracebase-rabinowitz-data#138
that the parent row can be legit missing if the compound is below the detection threshold, or it could be that the researcher just neglected to pick the peak.  He would like the code to warn and inpute the counts.
Count imputation was already happening, but the formula was wrong due to the fill down strategy.  I figured out a clever solution to the fill down by filling empty formulas won parent rows with a placeholder value and then replacing that in the fill down method with a Nan before back filling.
Details:
- Renamed MissingC12ParentPeakErrors to …
> Move missing parent catch to derived class

- DataRepo/loaders/base/converted_table_loader.py
- DataRepo/loaders/base/table_loader.py
- DataRepo/loaders/msruns_loader.py
- DataRepo/loaders/peak_annotations_loader.py
- DataRepo/loaders/study_loader.py
- DataRepo/management/commands/load_compounds.py
- DataRepo/management/commands/load_infusates.py
- DataRepo/management/commands/load_lcprotocols.py
- DataRepo/management/commands/load_msruns.py
- DataRepo/management/commands/load_protocols.py
- DataRepo/management/commands/load_samples.py
- DataRepo/management/commands/load_sequences.py
- DataRepo/management/commands/load_study.py
- DataRepo/management/commands/load_study_set.py
- DataRepo/management/commands/load_table.py
- DataRepo/management/commands/load_tissues.py
- DataRepo/management/commands/load_tracers.py
- DataRepo/tests/management/commands/test_load_table.py
- DataRepo/utils/exceptions.py
`AggregatedErrorsSet` is an exception class meant to contain a series of `AggregatedErrors` exception classes that are organized by both load file and overall checks, e.g. an accucor file, and a check like for missing samples (that can be repeated across multiple files)
`AggregatedErrors` is an exception class that contains all exceptions that arise from running an individual loader.
The problem was that some loaders run other loaders and thus raise `AggregatedErrorsSet` exceptions.  Mostly, this was correctly handled by either merging or appending the different types of errors into the appropriate object, but there was one place where I wasn't checking for `AggregatedErrorsSet` exceptions, which resulted in appending those exceptions to `AggregatedErrors` exceptions inappropriately. …
> Fixed minor bug where `AggregatedErrorsSet` exceptions were being buffered in `AggregatedErrors` exceptions

- DataRepo/tests/views/search/test_download.py
- DataRepo/views/search/download.py
Xi reported 500 server errors from the mzXML download button on the advanced search.
The web logs were devoid of errors and I could not reproduce the errors on either dev or prod, so I briefly enabled debug mode on prod and encountered the following exception:
```
Traceback (most recent call last):
File "/usr/local/tracebase/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
response = get_response(request)
File "/usr/local/tracebase/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/tracebase/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
return self.dispatch(request, *args, **kwargs)
File …
```
> Mzxml download 500 server error bugfix

- static/js/browser_download.js
- static/js/htmlSorter.js
Improved the htmlSorter, added alphanumeric and numeric sorters that will work on text with or without html, and make the browser download work on base64 encoded text.
> BST4: Javascript sort & export improvements

- DataRepo/models/utilities.py
- DataRepo/static/js/bst_list_view/filterer.js
- DataRepo/static/js/bst_list_view/sorter.js
- DataRepo/static/js/bst_list_view/value.js
- DataRepo/tests/models/test_utilities.py
- DataRepo/tests/static/js/bst_list_view/test_filterer.js
- DataRepo/tests/static/js/bst_list_view/test_sorter.js
- DataRepo/tests/static/js/bst_list_view/test_value.js
- DataRepo/tests/static/js/tests.html
- DataRepo/tests/tracebase_test_case.py
- DataRepo/tests/views/models/bst_list_view/test_filterer.py
- DataRepo/tests/views/models/bst_list_view/test_sorter.py
- DataRepo/views/models/bst_list_view/filterer.py
- DataRepo/views/models/bst_list_view/sorter.py
Added BSTFilterer and made minor improvements to the BSTSorter.
- Fixed some stale sorter documentation
- Moved `getSortValue` (and changed the name to `getVisibleValue`) to its own file (`value.js`)
- Changed the sorter behavior in string context to return the server or client sorter based on a new member: `client_mode`.
- Created an `assertNotWarns` decorator in the `TracebaseTestCase` classes.
- Created properties that render the sorter/filterer based on client mode.
- Added conditions to the warning about custom sorter/filterer arguments, to only happen when a corresponding transform/lookup is not provided
- Made `lookup` default to `contains` when a supplied field is a string field and choices are not provided
- Added client/server mode tests to the `BSTSorter` tests
- Added …
> BSTFilterer

- DataRepo/models/utilities.py
- DataRepo/templatetags/bst_list_view_tags.py
- DataRepo/templatetags/customtags.py
- DataRepo/tests/models/test_utilities.py
- DataRepo/tests/templatetags/test_bst_list_view_tags.py
- DataRepo/tests/templatetags/test_customtags.py
- resolve_field_path takes a Combinable, Field, or str and returns a field path, e.g. `msrun_sample__sample__animal__studies__name`
- Moved tags regarding detail urls, since they will/are only used in bst list view code.
- Partially addresses #1477
> Rearranged tags and added a model utility named `resolve_field_path`

- .htmlhintrc
- DataRepo/templates/models/bst_list_view/td.html
- DataRepo/templates/models/bst_list_view/th.html
- DataRepo/templates/models/bst_list_view/value.html
- DataRepo/tests/views/models/bst_list_view/test_column.py
- DataRepo/views/models/bst_list_view/column.py
- DataRepo/views/models/bst_list_view/filterer.py
Details:
- `BSTColumn` was made as a base class that only supports direct fields of a root model.
- It is planned to be used as a superclass for the following planned classes:
- `BSTAnnotColumn`
- `BSTRelatedColumn`
- `BSTManyRelatedColumn`
- It takes a set of simple arguments:
- Basics defining the column:
- `model`
- `field_path`
- `header`
- Boolean settings:
- `searchable`
- `sortable`
- `visible`
- `exported`
- `link` (whether it should link to the detail record)
- Functionality customization:
- `sorter` (a `BSTSorter`)
- `filterer` (a `BSTFilterer`)
- Templates (with generic defaults):
- `th_template` (`"models/bst_list_view/th.html"`)
- `td_template` (`"models/bst_list_view/bst_td.html"`)
- `value_template` (`"models/bst_list_view/bst_value.html"`)
- Class attributes used for …
> Added a `BSTColumn` class for a model's direct fields

- DataRepo/loaders/tracers_loader.py
- DataRepo/views/upload/submission.py
Addressed a column value type issue where the Label Positions column in the Tracers sheet was raising an exception when it contained only a single digit.
Some time back, casting of values to the expected type was removed from TableLoader.get_row_val because the type handling was left to Pandas.  It turned out that this might not have been a great improvement because Pandas has an issue with excel cells that are empty when the type doesn't permit null values.  This was mitigated by some related typing that only applies the type constraint when the column type is specified as `str`.  All other values are dynamically typed by Pandas, which deals fine with columns whose types don't allow null values, but they are mixed with values that are null.
The problem here was that the mecahnism to …
> Single label position bug fix

- static/js/hierarchical_formsets.js
Fixes a bug [introduced by commit a8f0c5c](https://github.com/Princeton-LSI-ResearchComputing/tracebase/commit/a8f0c5c4a91240b00f86f58fd23ecfd7ffbe81a6#diff-14871afcb6de82fdad4c581f0b55df1198b066799d0e935dc1db8e1e364e9e82L246-R247) which was trying to fix THIS bug.
The problem was that the FCirc format's initial ncmp select list had no default selection.  The fix had been to set the initial value BEFORE updating the choices.  However, the side-effect of that was to always set the first item in the select list.  So whenever a user selected a different value and submited a search, their search parameter for the ncmp select list would be changed.
The actual problem is that the ncmp choices are initially dictated by the first field in the selected template.  That first field in the peak group …
> The comparison select list on the advanced search gets reset each time you search

- DataRepo/loaders/base/table_loader.py
- DataRepo/tests/loaders/base/test_table_loader.py
- DataRepo/tests/utils/test_exceptions.py
- DataRepo/utils/exceptions.py
When an integrity error about a null required value comes up and the reported field ends with "_id", that string is removed to see if a field to column mapping exists.
Details:
- Also added a suggestion to the related errors, suggesting that it is likely the result of an upstream load (because otherwise there would be an error from the column requirements instead of the value error.
- Removed the field name from the error, as it is irrelevant to the user.
- Resolves #1517
- Specific …
> Fix for cryptic validation error when the field is a foreign key

- DataRepo/formats/dataformat.py
- DataRepo/models/utilities.py
- DataRepo/tests/models/test_utilities.py
- DataRepo/tests/views/search/test_download.py
Pulled changes to `DataRepo/models/utilities.py` from branch `bstlv4_paginate_queryset` in order to obtain the `get_distinct_fields` method, then modified that method to be able to only take the `model` argument and return all ordering fields.  Then I called that from `DataRepo.formats.dataformat.Format.getOrderByFields` when a given model **has** and ordering.
The problem was that `DataRepo.formats.dataformat.Format.getOrderByFields` assumed that a model's ordering only contained fields from its own model.  A recent change to `ArchiveFile` added fields to its ordering that included fields from other models, which caused the stats generation to fail with an `AttributeError`.
- Resolves #1533
- Checks out common code from:
- PR #1535
- branch …
> Advanced Search Stats bug fix

- DataRepo/management/commands/load_peak_annotations.py
Just noticed a copy-paste-o while loading data on pub.
> Corrected the default sheet name for the peak group conflicts sheet

- DataRepo/static/js/bst/cookies.js
- DataRepo/templates/models/bst/list_view.html
- DataRepo/templates/models/bst/th.html
- DataRepo/tests/static/js/bst/test_cookies.js
- DataRepo/tests/static/js/tests.html
- DataRepo/tests/templates/models/bst/base_template_test.py
- DataRepo/tests/templates/models/bst/test_list_view.py
- DataRepo/tests/templates/models/bst/test_td.py
- DataRepo/tests/templates/models/bst/test_th.py
- DataRepo/tests/views/models/bst/column/filterer/test_annotation.py
- DataRepo/tests/views/models/bst/column/filterer/test_field.py
- DataRepo/tests/views/models/bst/column/sorter/test_annotation.py
- DataRepo/tests/views/models/bst/column/sorter/test_field.py
- DataRepo/tests/views/models/bst/test_base.py
- DataRepo/tests/views/models/bst/test_client_interface.py
- DataRepo/tests/views/models/bst/test_list_view.py
- DataRepo/views/models/bst/base.py
- DataRepo/views/models/bst/client_interface.py
- DataRepo/views/models/bst/column/annotation.py
- DataRepo/views/models/bst/column/base.py
- DataRepo/views/models/bst/column/field.py
- DataRepo/views/models/bst/column/filterer/base.py
- DataRepo/views/models/bst/column/many_related_field.py
- DataRepo/views/models/bst/column/related_field.py
- DataRepo/views/models/bst/column/sorter/base.py
- DataRepo/views/models/bst/list_view.py
- static/js/cookies.js
Wrote tests for the `list_view`, `th`, and `td` BST templates, updated the `value` template tests, and made a bunch of changes based on those tests.
The instigating issue was populating the column select list filters.  This was done by switching from the javascript `obj` strategy in the original prototype to using the `json` strategy, so that passing the select list content could be done via the column context variables and the logic contained in the `th` template instead of it having to be handled in the overall javascript for each listview page.
Details:
- Renamed `BSTBaseFilterer.filter` method to `create_q_exp`, for clarity.  ("filter" was too overloaded)
- Removed the script property from the `filterer` and `sorter` classes, because they all refer to the same script, and importing …
> `BSTListView` 7: Templates

- DataRepo/templates/models/bst/th.html
- DataRepo/tests/templates/models/bst/test_th.py
- DataRepo/tests/views/models/bst/column/test_field.py
- DataRepo/tests/views/models/bst/column/test_many_related_field.py
- DataRepo/tests/views/models/bst/column/test_related_field.py
- DataRepo/tests/views/models/bst/test_base.py
- DataRepo/tests/views/models/bst/test_client_interface.py
- DataRepo/tests/views/models/bst/test_list_view.py
- DataRepo/views/models/bst/base.py
- DataRepo/views/models/bst/client_interface.py
- DataRepo/views/models/bst/column/base.py
- DataRepo/views/models/bst/column/related_field.py
Fixed the redundant paginator, added a tooltip for headers with no search/sort, and made count columns distinct.
Details:
- A tooltip is created when a foreign key column to a model with no representative to explain why search/sort is not enabled.
- Set is_paginated to None so that the vanilla paginator isn't rendered under the SizedPaginator.
- Made automatically added count columns use distinct=True.
- Partially addresses #1585
- Specifically, the following issues in [this comment](https://github.com/Princeton-LSI-ResearchComputing/tracebase/issues/1585#issuecomment-2968130096) were addressed:
- The paginator from the base template is redundantly displaying (e.g. "Page 1 of 179. next" at the bottom of the page)
- Add a tooltip to make it clear that the reason there is no filter is …
> `BSTListView` 15.8: Removed duplicate paginator, explained disabled search/sort, and made count column counts distinct

- DataRepo/static/js/bst/list_view.js
- DataRepo/templates/models/bst/scripts.html
- DataRepo/templates/models/bst/th.html
- DataRepo/tests/templates/models/bst/test_th.py
- DataRepo/tests/views/models/bst/column/test_field.py
- DataRepo/tests/views/models/bst/column/test_many_related_field.py
- DataRepo/tests/views/models/bst/column/test_related_field.py
- DataRepo/tests/views/models/bst/test_base.py
- DataRepo/tests/views/models/bst/test_client_interface.py
- DataRepo/tests/views/models/bst/test_list_view.py
- DataRepo/tests/widgets/bst/test_rows_per_page_select.py
- DataRepo/utils/exceptions.py
- DataRepo/views/models/bst/base.py
- DataRepo/views/models/bst/client_interface.py
- DataRepo/views/models/bst/column/base.py
- DataRepo/views/models/bst/column/related_field.py
- DataRepo/views/models/bst/list_view.py
- DataRepo/views/models/bst/utils.py
- DataRepo/widgets/bst/rows_per_page_select.py
Fixed rows per page issues
Details:
- BSTRowsPerPageSelect changes:
- filter_page_sizes not keeps selections that are less than or equal to the selected rows per page (to be able to maintain the user's manual selection).
- Only add a custom selected page size if it is not euqal to the total number of rows available and if it is equal to the total rows, set the rows per page to 0 ("ALL").
- Corrected a keyword argument in SizedPaginator in the instantiation of BSTRowsPerPageSelect that was supplied as a positional arg.
- Added a trace to a warning in BSTListView.
- Changed the setting of limit in BSTClientInterface so that it does not override the user's selected rows per page when the total rows are less than the slected rows per page.
- Improved the trace exception method to add an …
> `BSTListView` 15.7: Fixed rows per page issues

- DataRepo/models/utilities.py
- DataRepo/static/js/bst/list_view.js
- DataRepo/templates/models/bst/th.html
- DataRepo/tests/models/test_utilities.py
- DataRepo/tests/templates/models/bst/test_th.py
- DataRepo/tests/views/models/bst/column/filterer/test_base.py
- DataRepo/tests/views/models/bst/column/filterer/test_field.py
- DataRepo/tests/views/models/bst/column/test_annotation.py
- DataRepo/tests/views/models/bst/column/test_field.py
- DataRepo/tests/views/models/bst/column/test_related_field.py
- DataRepo/tests/views/models/bst/test_base.py
- DataRepo/tests/views/models/bst/test_client_interface.py
- DataRepo/tests/views/models/bst/test_list_view.py
- DataRepo/views/models/bst/base.py
- DataRepo/views/models/bst/client_interface.py
- DataRepo/views/models/bst/column/annotation.py
- DataRepo/views/models/bst/column/field.py
- DataRepo/views/models/bst/column/filterer/base.py
- DataRepo/views/models/bst/column/filterer/field.py
- DataRepo/views/models/bst/column/related_field.py
This is the last PR before I push updates to the `SampleListView` class.  It's the "final push", so there's a bit more in here size-wise than previous PRs.
Added the ability to search for "None", removed the related model name from headers, fixed the auto-addition of count columns, fixed the usage of field verbose names, fixed cookie resets, and added a tooltip to all non-count columns that have a single field associated with them.
Details:
- `BSTRelatedColumn`
- Removed the parent model from header construction.
- `BSTFilterer`
- Modified choices dict values to include the key if the key and value differ.
- `BSTBaseFilterer`
- Added a special case when `term` == "None" to create an `isnull` filter.
- `BSTColumn`
- Added a `tooltip` to include `self.field.help_text`.
- `BSTAnnotColumn`
- …
> `BSTListView` 15.12: None-search, header-tweaks, count-columns, verbose-names, cookie-resets, and annotation-tooltips

- DataRepo/models/utilities.py
- DataRepo/static/js/bst/list_view.js
- DataRepo/templates/models/bst/scripts.html
- DataRepo/templates/models/bst/th.html
- DataRepo/templatetags/bsttags.py
- DataRepo/tests/models/test_utilities.py
- DataRepo/tests/static/js/bst/test_list_view.js
- DataRepo/tests/templates/models/bst/test_th.py
- DataRepo/tests/templatetags/test_bsttags.py
- DataRepo/tests/views/models/bst/column/filterer/test_base.py
- DataRepo/tests/views/models/bst/column/filterer/test_field.py
- DataRepo/tests/views/models/bst/column/test_annotation.py
- DataRepo/tests/views/models/bst/column/test_base.py
- DataRepo/tests/views/models/bst/column/test_field.py
- DataRepo/tests/views/models/bst/column/test_related_field.py
- DataRepo/tests/views/models/bst/test_base.py
- DataRepo/tests/views/models/bst/test_client_interface.py
- DataRepo/tests/views/models/bst/test_list_view.py
- DataRepo/views/models/bst/base.py
- DataRepo/views/models/bst/client_interface.py
- DataRepo/views/models/bst/column/annotation.py
- DataRepo/views/models/bst/column/base.py
- DataRepo/views/models/bst/column/field.py
- DataRepo/views/models/bst/column/filterer/base.py
- DataRepo/views/models/bst/column/filterer/field.py
- DataRepo/views/models/bst/column/related_field.py
I started fleshing the `SampleListView` class with custom columns and ran into some more minor bugs.
Fixed column visibility cookies and exceptions regarding representative fields, null foreign keys, and setting conflicts.
Details:
- `BSTBaseColumn`
- Added instance attribute `hidable` to `BSTBaseColumn`.
- `BSTBaseListView`
- `init_interface`
- Added a set for `column.visible` from the cookies in `init_interface`.
- Deleted bad visible cookies.
- `init_column_settings`
- Only raise `ProgrammingError` when the annotation conflict is specifically with "converter".  This allows derived classes to tweak the settings of an annotation column.
- `init_column_setting`
- Added a check for conflicting annotations (with column objects).
- `init_column_setting`
- Changed `ValueError`s to …
> `BSTListView` 15.11: Fixed column visibility, representative fields, null foreign keys, and setting conflicts

- DataRepo/models/utilities.py
- DataRepo/static/js/bst/list_view.js
- DataRepo/templates/models/bst/scripts.html
- DataRepo/templates/models/bst/th.html
- DataRepo/templatetags/bsttags.py
- DataRepo/tests/models/test_utilities.py
- DataRepo/tests/static/js/bst/test_list_view.js
- DataRepo/tests/templates/models/bst/test_th.py
- DataRepo/tests/templatetags/test_bsttags.py
- DataRepo/tests/tracebase_test_case.py
- DataRepo/tests/views/models/bst/column/filterer/test_base.py
- DataRepo/tests/views/models/bst/column/filterer/test_field.py
- DataRepo/tests/views/models/bst/column/test_annotation.py
- DataRepo/tests/views/models/bst/column/test_base.py
- DataRepo/tests/views/models/bst/column/test_field.py
- DataRepo/tests/views/models/bst/column/test_related_field.py
- DataRepo/tests/views/models/bst/test_base.py
- DataRepo/tests/views/models/bst/test_client_interface.py
- DataRepo/tests/views/models/bst/test_list_view.py
- DataRepo/views/models/bst/base.py
- DataRepo/views/models/bst/client_interface.py
- DataRepo/views/models/bst/column/annotation.py
- DataRepo/views/models/bst/column/base.py
- DataRepo/views/models/bst/column/field.py
- DataRepo/views/models/bst/column/filterer/base.py
- DataRepo/views/models/bst/column/filterer/field.py
- DataRepo/views/models/bst/column/related_field.py
- DataRepo/views/models/bst/list_view.py
Added the ability to set column_settings in a class attribute and supply kwargs for the sorter and filterer constructors via the BSTBaseListView constructor's sorter and filterer arguments.
Details:
- Added an example to the docstrings for classes `BSTListView` and `BSTBaseListView`
- Made the `BSTBaseFilterer` constructor's `choices` option take a callable so that DB queries wouldn't happen at the class attribute level when setting the drop-down list content.
- `BSTFilterer`
- Renamed `select_list` to `has_select_list` for clarity.
- Removed calls to `len()` on `choices` because of the type change.  This means that it no longer detects empty `choices` when handling `distinct_choices`.  `choices` must be `None` or populated.
- Added a `TODO` comment to make `model` an optional keyword …
> `BSTListView` 15.10: Added a way to init `column_settings` as a class attribute

- DataRepo/models/utilities.py
- DataRepo/tests/views/models/bst_list_view/column/test_field.py
- DataRepo/views/models/bst_list_view/column/base.py
- DataRepo/views/models/bst_list_view/column/field.py
Turned `is_fk` into an instance attribute of the `BSTColumn` class instead of a class attribute of the `BSTBaseColumn` class.
I realized that `is_fk` is not necessarily a characteristic exclusive to the planned `BSTRelatedColumn`.  A regular `Field` column (i.e. `BSTColumn`) can have fields that are foreign keys and they can be linked whether or not we've defined a `BSTRelatedColumn`.  The features that `BSTRelatedColumn` will allow is the specification of a display value instead of how a related model object happens to render in str context.  Just note that the foreign key cannot be searched or sorted based on that string-context value.  That's what defining a `BSTRelatedColumn` will provide.
Details:
- Created a model utility method named `is_key_field`
- Defaulted `is_fk` in the …
> Integrated base class support for foreign keys

- DataRepo/management/commands/build_cached_fields.py
- DataRepo/models/hier_cached_model.py
This doesn't solve the download speed issue, but it is a significant factor.  I will update the `nplcadmindocs` to include running this after a load.
This involved adding a class method to `HierCachedModel`: `build_cached_fields`.
Note the usage output:
```
$ python manage.py build_cached_fields -h
usage: manage.py build_cached_fields [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH] [--traceback] [--no-color] [--force-color] [--skip-checks] [--models [MODELS ...]] [--functions [FUNCTIONS ...]] [--clear]
Builds missing cached values for all model fields with the following cached_functions:
Animal
tracers
last_serum_tracer_peak_groups
tracer_links
AnimalLabel
tracers
last_serum_tracer_label_peak_groups
serum_tracers_enrichment_fraction
FCirc …
```
> Build Cache Script (a download speed issue)

- DataRepo/tests/views/models/bst/column/test_field.py
- DataRepo/tests/views/models/bst/column/test_many_related_field.py
- DataRepo/tests/views/models/bst/column/test_related_field.py
- DataRepo/views/models/bst/column/field.py
- DataRepo/views/models/bst/column/related_field.py
Fixed an issue where the headers for reverse related fields were being derived from the related model's field name instead of from the foreign key name (which provides context).
Details:
- Added override method BSTRelatedColumn.generate_header.
- Removed related model logic from BSTColumn.generate_header.
- Fixed constructor arguments given as keyword arguments in test_field.py.
- Added `unique=True` to the temp Animal model in test_related_field.py in order to test generated headfers of reverse relations.
Examples from the Sample List page:
- Header for reverse related field `Animal.last_serum_sample` (whose `related_name` is `animals`) was getting a generated header of `Last Serum Sample` and now is `Animals`
- Note: `animals` is a bad related name, but that is a separate issue from …
> `BSTListView` 15.2: Fixed a header naming issue with reverse relations

- DataRepo/static/js/bst/list_view.js
- DataRepo/templates/models/bst/scripts.html
- DataRepo/tests/static/js/bst/test_list_view.js
- DataRepo/tests/templates/models/bst/test_list_view.py
- DataRepo/tests/tracebase_test_case.py
- DataRepo/tests/views/models/bst/test_base.py
- DataRepo/tests/views/models/bst/test_client_interface.py
- DataRepo/tests/views/models/bst/test_list_view.py
- DataRepo/views/models/bst/base.py
- DataRepo/views/models/bst/client_interface.py
- DataRepo/views/models/bst/list_view.py
See the Affected Issues section for the issues that this PR addresses.  Review of this PR is limited to satisfying those specific issues.
The strategy I'd used to initialize cookies in the constructor worked for tests, but when there's a real view, Django is the one calling the view constructor, and it doesn't supply the request object..
I had been lead astray by some example code online and in Django documentation that showed the request object being supplied to a view's constructor, which I'd assumed is how the django view constructors are called.  Doing so works, but apparently when a `GET` request comes in, the constructor is not supplied the request.  The first place that's available is in the `get` method.  I tried initially to simply move code into `get` method extensions, but that …
> `BSTListView` 15.3: Fixed cookie init strategy

- DataRepo/loaders/base/table_loader.py
- DataRepo/tests/loaders/base/test_table_loader.py
Fixed a bug where `handle_load_db_errors` was comparing the new record `dict` with the wrong existing database record due to not including the `UniqueConstraint.condition`.
Details:
- Updated some type annotations in existing methods
- ~Made `TableLoader.check_for_inconsistencies` account for populated DB record fields that are not represented in the `rec_dict`.~ I pulled this change out to put in a separate PR.
- Renamed `TableLoader.get_unique_constraint_fields` to `get_unique_constraints` and changed the return type from `List[str]` to `List[UniqueConstraint]` so that `condition` would be accessible.
- `TableLoader.handle_load_db_errors`
- Split up the unique fields and `UniqueConstraint` processing in order to be able to treat them differently.
- Simplified the processing of unique …
> Fixed a `TableLoader` bug in `handle_load_db_errors` that was comparing the new record dict with the wrong existing database record

- DataRepo/loaders/base/table_loader.py
- DataRepo/tests/loaders/base/test_table_loader.py
- DataRepo/tests/loaders/test_samples_loader.py
Made `TableLoader.check_for_inconsistencies` account for populated DB record fields not represented in the `rec_dict`.
- Edited test_check_for_inconsistencies_case3 to provide debug info when my initial test run failed that test
- Edited test_get_or_create_sample_date_time_and_unique_error to provide debug info about fields that were not in the infile columns, like Sample.is_serum_sample.
- Compared to my initial attempt at this change in the previous PR, I added a check that the DB field is in FieldToDataHeaderKey to ensure that the reported differences are ones that a researcher can do something about.
- Resolves no documented GitHub issue
- Resolves [GREATS-79](https://princeton-university.atlassian.net/browse/GREATS-89?atlOrigin=eyJpIjoiZjYzMzliNWY0NjM1NGM1NDgzOWQ5ODc2MDE0NThhNzQiLCJwI …
> Made `TableLoader.check_for_inconsistencies` account for populated DB record fields not represented in the `rec_dict`
